
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  8 2023 18:49:27 IST (May  8 2023 13:19:27 UTC)

// Verification Directory fv/async_fifo1 

module async_fifo1(winc, wclk, wrst_n, rinc, rclk, rrst_n, wdata,
     rdata, wfull, rempty);
  input winc, wclk, wrst_n, rinc, rclk, rrst_n;
  input [7:0] wdata;
  output [7:0] rdata;
  output wfull, rempty;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [7:0] \MEM_memo[0] ;
  wire [7:0] \MEM_memo[1] ;
  wire [7:0] \MEM_memo[2] ;
  wire [7:0] \MEM_memo[3] ;
  wire [7:0] \MEM_memo[4] ;
  wire [7:0] \MEM_memo[5] ;
  wire [7:0] \MEM_memo[6] ;
  wire [7:0] \MEM_memo[7] ;
  wire [7:0] \MEM_memo[8] ;
  wire [7:0] \MEM_memo[9] ;
  wire [7:0] \MEM_memo[10] ;
  wire [7:0] \MEM_memo[11] ;
  wire [7:0] \MEM_memo[12] ;
  wire [7:0] \MEM_memo[13] ;
  wire [7:0] \MEM_memo[14] ;
  wire [7:0] \MEM_memo[15] ;
  wire [4:0] rptr;
  wire [4:0] R2W_wq1_rptr;
  wire [4:0] wq2_rptr;
  wire [3:0] raddr;
  wire [4:0] RPTR_rgraynext;
  wire [4:0] rq2_wptr;
  wire [4:0] RPTR_rbinnext;
  wire [4:0] wptr;
  wire [4:0] W2R_rq1_wptr;
  wire [3:0] waddr;
  wire [4:0] WPTR_wgraynext;
  wire [4:0] WPTR_wbinnext;
  wire MEM_n_360, MEM_n_361, MEM_n_362, MEM_n_363, MEM_n_364,
       MEM_n_365, MEM_n_366, MEM_n_367;
  wire MEM_n_368, MEM_n_369, MEM_n_370, MEM_n_371, MEM_n_372,
       MEM_n_373, MEM_n_374, MEM_n_375;
  wire R2W_n_49, RPTR_n_29, RPTR_n_65, RPTR_n_66, RPTR_n_68, RPTR_n_85,
       RPTR_n_87, RPTR_n_89;
  wire RPTR_n_91, RPTR_n_92, RPTR_n_113, RPTR_n_114, RPTR_n_115,
       RPTR_n_116, RPTR_n_117, RPTR_n_118;
  wire RPTR_n_133, RPTR_n_134, RPTR_n_135, RPTR_n_136, RPTR_n_137,
       RPTR_n_138, RPTR_n_139, RPTR_n_140;
  wire RPTR_n_141, RPTR_n_142, RPTR_n_143, RPTR_n_144, RPTR_n_145,
       RPTR_n_146, RPTR_n_147, RPTR_n_148;
  wire RPTR_n_149, RPTR_n_150, RPTR_n_151, RPTR_n_152, RPTR_n_153,
       RPTR_n_154, RPTR_n_155, RPTR_n_156;
  wire RPTR_n_157, RPTR_n_158, RPTR_rempty_val, W2R_n_49, WPTR_n_31,
       WPTR_n_67, WPTR_n_68, WPTR_n_70;
  wire WPTR_n_87, WPTR_n_89, WPTR_n_91, WPTR_n_93, WPTR_n_94,
       WPTR_n_115, WPTR_n_116, WPTR_n_117;
  wire WPTR_n_118, WPTR_n_119, WPTR_n_120, WPTR_n_135, WPTR_n_136,
       WPTR_n_137, WPTR_n_138, WPTR_n_139;
  wire WPTR_n_140, WPTR_n_141, WPTR_n_142, WPTR_n_143, WPTR_n_144,
       WPTR_n_145, WPTR_n_146, WPTR_n_147;
  wire WPTR_n_148, WPTR_n_149, WPTR_n_150, WPTR_n_151, WPTR_n_152,
       WPTR_n_153, WPTR_n_154, WPTR_n_155;
  wire WPTR_n_156, WPTR_n_157, WPTR_n_158, WPTR_n_159, WPTR_n_160,
       WPTR_wfull_val, n_397, n_398;
  wire n_399, n_400, n_401, n_402, n_403, n_404, n_405, n_406;
  wire n_407, n_408, n_409, n_410, n_411, n_412, n_417, n_418;
  wire n_419, n_420, n_421, n_422, n_423, n_424, n_427, n_428;
  wire n_429, n_430, n_434, n_437, n_440, n_443, n_472, n_473;
  wire n_474, n_475, n_476, n_477, n_478, n_479, n_480, n_481;
  wire n_482, n_483, n_484, n_485, n_514, n_515, n_516, n_517;
  wire n_518, n_519, n_520, n_521, n_522, n_523, n_524, n_525;
  wire n_526, n_527, n_556, n_557, n_558, n_559, n_560, n_561;
  wire n_562, n_563, n_564, n_565, n_566, n_567, n_568, n_569;
  wire n_598, n_599, n_600, n_601, n_602, n_603, n_604, n_605;
  wire n_606, n_607, n_608, n_609, n_610, n_611, n_640, n_641;
  wire n_642, n_643, n_644, n_645, n_646, n_647, n_648, n_649;
  wire n_650, n_651, n_652, n_653, n_682, n_683, n_684, n_685;
  wire n_686, n_687, n_688, n_689, n_690, n_691, n_692, n_693;
  wire n_694, n_695, n_724, n_725, n_726, n_727, n_728, n_729;
  wire n_730, n_731, n_732, n_733, n_734, n_735, n_736, n_737;
  wire n_766, n_767, n_768, n_769, n_770, n_771, n_772, n_773;
  wire n_774, n_775, n_776, n_777, n_778, n_779, n_808, n_809;
  wire n_810, n_811, n_812, n_813, n_814, n_815, n_816, n_817;
  wire n_818, n_819, n_820, n_821, n_850, n_851, n_852, n_853;
  wire n_854, n_855, n_856, n_857, n_858, n_859, n_860, n_861;
  wire n_862, n_863, n_892, n_893, n_894, n_895, n_896, n_897;
  wire n_898, n_899, n_900, n_901, n_902, n_903, n_904, n_905;
  wire n_934, n_935, n_936, n_937, n_938, n_939, n_940, n_941;
  wire n_942, n_943, n_944, n_945, n_946, n_947, n_976, n_977;
  wire n_978, n_979, n_980, n_981, n_982, n_983, n_984, n_985;
  wire n_986, n_987, n_988, n_989, n_1018, n_1019, n_1020, n_1021;
  wire n_1022, n_1023, n_1024, n_1025, n_1026, n_1027, n_1028, n_1029;
  wire n_1030, n_1031, n_1060, n_1061, n_1062, n_1063, n_1064, n_1065;
  wire n_1066, n_1067, n_1068, n_1069, n_1070, n_1071, n_1072, n_1073;
  wire n_1102, n_1103, n_1104, n_1105, n_1106, n_1107, n_1108, n_1109;
  wire n_1110, n_1111, n_1112, n_1113, n_1114, n_1115, n_1118, n_1121;
  wire n_1126, n_1127, n_1132, n_1133, n_1138, n_1139, n_1144, n_1145;
  wire n_1150, n_1151, n_1156, n_1157, n_1162, n_1163, n_1168, n_1169;
  wire n_1172, n_1175, n_1178, n_1181, n_1184, n_1187, n_1190, n_1193;
  CDN_flop \MEM_memo_reg[0][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [0]));
  CDN_flop \MEM_memo_reg[0][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [1]));
  CDN_flop \MEM_memo_reg[0][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [2]));
  CDN_flop \MEM_memo_reg[0][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [3]));
  CDN_flop \MEM_memo_reg[0][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [4]));
  CDN_flop \MEM_memo_reg[0][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [5]));
  CDN_flop \MEM_memo_reg[0][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [6]));
  CDN_flop \MEM_memo_reg[0][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_360), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[0] [7]));
  CDN_flop \MEM_memo_reg[1][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [0]));
  CDN_flop \MEM_memo_reg[1][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [1]));
  CDN_flop \MEM_memo_reg[1][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [2]));
  CDN_flop \MEM_memo_reg[1][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [3]));
  CDN_flop \MEM_memo_reg[1][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [4]));
  CDN_flop \MEM_memo_reg[1][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [5]));
  CDN_flop \MEM_memo_reg[1][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [6]));
  CDN_flop \MEM_memo_reg[1][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_361), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[1] [7]));
  CDN_flop \MEM_memo_reg[2][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [0]));
  CDN_flop \MEM_memo_reg[2][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [1]));
  CDN_flop \MEM_memo_reg[2][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [2]));
  CDN_flop \MEM_memo_reg[2][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [3]));
  CDN_flop \MEM_memo_reg[2][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [4]));
  CDN_flop \MEM_memo_reg[2][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [5]));
  CDN_flop \MEM_memo_reg[2][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [6]));
  CDN_flop \MEM_memo_reg[2][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_362), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[2] [7]));
  CDN_flop \MEM_memo_reg[3][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [0]));
  CDN_flop \MEM_memo_reg[3][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [1]));
  CDN_flop \MEM_memo_reg[3][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [2]));
  CDN_flop \MEM_memo_reg[3][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [3]));
  CDN_flop \MEM_memo_reg[3][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [4]));
  CDN_flop \MEM_memo_reg[3][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [5]));
  CDN_flop \MEM_memo_reg[3][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [6]));
  CDN_flop \MEM_memo_reg[3][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_363), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[3] [7]));
  CDN_flop \MEM_memo_reg[4][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [0]));
  CDN_flop \MEM_memo_reg[4][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [1]));
  CDN_flop \MEM_memo_reg[4][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [2]));
  CDN_flop \MEM_memo_reg[4][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [3]));
  CDN_flop \MEM_memo_reg[4][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [4]));
  CDN_flop \MEM_memo_reg[4][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [5]));
  CDN_flop \MEM_memo_reg[4][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [6]));
  CDN_flop \MEM_memo_reg[4][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_364), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[4] [7]));
  CDN_flop \MEM_memo_reg[5][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [0]));
  CDN_flop \MEM_memo_reg[5][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [1]));
  CDN_flop \MEM_memo_reg[5][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [2]));
  CDN_flop \MEM_memo_reg[5][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [3]));
  CDN_flop \MEM_memo_reg[5][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [4]));
  CDN_flop \MEM_memo_reg[5][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [5]));
  CDN_flop \MEM_memo_reg[5][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [6]));
  CDN_flop \MEM_memo_reg[5][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_365), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[5] [7]));
  CDN_flop \MEM_memo_reg[6][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [0]));
  CDN_flop \MEM_memo_reg[6][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [1]));
  CDN_flop \MEM_memo_reg[6][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [2]));
  CDN_flop \MEM_memo_reg[6][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [3]));
  CDN_flop \MEM_memo_reg[6][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [4]));
  CDN_flop \MEM_memo_reg[6][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [5]));
  CDN_flop \MEM_memo_reg[6][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [6]));
  CDN_flop \MEM_memo_reg[6][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_366), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[6] [7]));
  CDN_flop \MEM_memo_reg[7][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [0]));
  CDN_flop \MEM_memo_reg[7][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [1]));
  CDN_flop \MEM_memo_reg[7][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [2]));
  CDN_flop \MEM_memo_reg[7][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [3]));
  CDN_flop \MEM_memo_reg[7][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [4]));
  CDN_flop \MEM_memo_reg[7][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [5]));
  CDN_flop \MEM_memo_reg[7][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [6]));
  CDN_flop \MEM_memo_reg[7][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_367), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[7] [7]));
  CDN_flop \MEM_memo_reg[8][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [0]));
  CDN_flop \MEM_memo_reg[8][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [1]));
  CDN_flop \MEM_memo_reg[8][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [2]));
  CDN_flop \MEM_memo_reg[8][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [3]));
  CDN_flop \MEM_memo_reg[8][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [4]));
  CDN_flop \MEM_memo_reg[8][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [5]));
  CDN_flop \MEM_memo_reg[8][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [6]));
  CDN_flop \MEM_memo_reg[8][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_368), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[8] [7]));
  CDN_flop \MEM_memo_reg[9][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [0]));
  CDN_flop \MEM_memo_reg[9][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [1]));
  CDN_flop \MEM_memo_reg[9][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [2]));
  CDN_flop \MEM_memo_reg[9][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [3]));
  CDN_flop \MEM_memo_reg[9][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [4]));
  CDN_flop \MEM_memo_reg[9][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [5]));
  CDN_flop \MEM_memo_reg[9][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [6]));
  CDN_flop \MEM_memo_reg[9][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_369), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[9] [7]));
  CDN_flop \MEM_memo_reg[10][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [0]));
  CDN_flop \MEM_memo_reg[10][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [1]));
  CDN_flop \MEM_memo_reg[10][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [2]));
  CDN_flop \MEM_memo_reg[10][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [3]));
  CDN_flop \MEM_memo_reg[10][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [4]));
  CDN_flop \MEM_memo_reg[10][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [5]));
  CDN_flop \MEM_memo_reg[10][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [6]));
  CDN_flop \MEM_memo_reg[10][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_370), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[10] [7]));
  CDN_flop \MEM_memo_reg[11][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [0]));
  CDN_flop \MEM_memo_reg[11][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [1]));
  CDN_flop \MEM_memo_reg[11][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [2]));
  CDN_flop \MEM_memo_reg[11][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [3]));
  CDN_flop \MEM_memo_reg[11][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [4]));
  CDN_flop \MEM_memo_reg[11][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [5]));
  CDN_flop \MEM_memo_reg[11][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [6]));
  CDN_flop \MEM_memo_reg[11][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_371), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[11] [7]));
  CDN_flop \MEM_memo_reg[12][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [0]));
  CDN_flop \MEM_memo_reg[12][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [1]));
  CDN_flop \MEM_memo_reg[12][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [2]));
  CDN_flop \MEM_memo_reg[12][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [3]));
  CDN_flop \MEM_memo_reg[12][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [4]));
  CDN_flop \MEM_memo_reg[12][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [5]));
  CDN_flop \MEM_memo_reg[12][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [6]));
  CDN_flop \MEM_memo_reg[12][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_372), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[12] [7]));
  CDN_flop \MEM_memo_reg[13][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [0]));
  CDN_flop \MEM_memo_reg[13][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [1]));
  CDN_flop \MEM_memo_reg[13][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [2]));
  CDN_flop \MEM_memo_reg[13][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [3]));
  CDN_flop \MEM_memo_reg[13][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [4]));
  CDN_flop \MEM_memo_reg[13][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [5]));
  CDN_flop \MEM_memo_reg[13][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [6]));
  CDN_flop \MEM_memo_reg[13][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_373), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[13] [7]));
  CDN_flop \MEM_memo_reg[14][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [0]));
  CDN_flop \MEM_memo_reg[14][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [1]));
  CDN_flop \MEM_memo_reg[14][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [2]));
  CDN_flop \MEM_memo_reg[14][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [3]));
  CDN_flop \MEM_memo_reg[14][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [4]));
  CDN_flop \MEM_memo_reg[14][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [5]));
  CDN_flop \MEM_memo_reg[14][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [6]));
  CDN_flop \MEM_memo_reg[14][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_374), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[14] [7]));
  CDN_flop \MEM_memo_reg[15][0] (.clk (wclk), .d (wdata[0]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [0]));
  CDN_flop \MEM_memo_reg[15][1] (.clk (wclk), .d (wdata[1]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [1]));
  CDN_flop \MEM_memo_reg[15][2] (.clk (wclk), .d (wdata[2]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [2]));
  CDN_flop \MEM_memo_reg[15][3] (.clk (wclk), .d (wdata[3]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [3]));
  CDN_flop \MEM_memo_reg[15][4] (.clk (wclk), .d (wdata[4]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [4]));
  CDN_flop \MEM_memo_reg[15][5] (.clk (wclk), .d (wdata[5]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [5]));
  CDN_flop \MEM_memo_reg[15][6] (.clk (wclk), .d (wdata[6]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [6]));
  CDN_flop \MEM_memo_reg[15][7] (.clk (wclk), .d (wdata[7]), .sena
       (MEM_n_375), .aclr (1'b0), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (\MEM_memo[15] [7]));
  not R2W_g1 (R2W_n_49, wrst_n);
  CDN_flop \R2W_wq1_rptr_reg[0] (.clk (wclk), .d (rptr[0]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (R2W_wq1_rptr[0]));
  CDN_flop \R2W_wq1_rptr_reg[1] (.clk (wclk), .d (rptr[1]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (R2W_wq1_rptr[1]));
  CDN_flop \R2W_wq1_rptr_reg[2] (.clk (wclk), .d (rptr[2]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (R2W_wq1_rptr[2]));
  CDN_flop \R2W_wq1_rptr_reg[3] (.clk (wclk), .d (rptr[3]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (R2W_wq1_rptr[3]));
  CDN_flop \R2W_wq1_rptr_reg[4] (.clk (wclk), .d (rptr[4]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (R2W_wq1_rptr[4]));
  CDN_flop \R2W_wq2_rptr_reg[0] (.clk (wclk), .d (R2W_wq1_rptr[0]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wq2_rptr[0]));
  CDN_flop \R2W_wq2_rptr_reg[1] (.clk (wclk), .d (R2W_wq1_rptr[1]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wq2_rptr[1]));
  CDN_flop \R2W_wq2_rptr_reg[2] (.clk (wclk), .d (R2W_wq1_rptr[2]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wq2_rptr[2]));
  CDN_flop \R2W_wq2_rptr_reg[3] (.clk (wclk), .d (R2W_wq1_rptr[3]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wq2_rptr[3]));
  CDN_flop \R2W_wq2_rptr_reg[4] (.clk (wclk), .d (R2W_wq1_rptr[4]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wq2_rptr[4]));
  or RPTR_g49 (RPTR_n_87, RPTR_n_91, wc);
  not gc (wc, raddr[3]);
  or RPTR_g67 (RPTR_n_68, RPTR_n_113, RPTR_n_114);
  or RPTR_g91 (RPTR_n_113, RPTR_n_117, RPTR_n_118);
  nand RPTR_g92 (RPTR_n_117, RPTR_n_65, RPTR_n_66);
  nand RPTR_g93 (RPTR_n_133, RPTR_rgraynext[3], rq2_wptr[3]);
  or RPTR_g94 (RPTR_n_134, RPTR_rgraynext[3], rq2_wptr[3]);
  nand RPTR_g95 (RPTR_n_66, RPTR_n_133, RPTR_n_134);
  or RPTR_g96 (RPTR_n_135, wc0, RPTR_rbinnext[3]);
  not gc0 (wc0, RPTR_rbinnext[4]);
  or RPTR_g97 (RPTR_n_136, RPTR_rbinnext[4], wc1);
  not gc1 (wc1, RPTR_rbinnext[3]);
  nand RPTR_g98 (RPTR_rgraynext[3], RPTR_n_135, RPTR_n_136);
  nand RPTR_g99 (RPTR_n_137, RPTR_rbinnext[4], rq2_wptr[4]);
  or RPTR_g100 (RPTR_n_138, RPTR_rbinnext[4], rq2_wptr[4]);
  nand RPTR_g101 (RPTR_n_92, RPTR_n_137, RPTR_n_138);
  nand RPTR_g102 (RPTR_n_139, RPTR_rgraynext[2], rq2_wptr[2]);
  or RPTR_g103 (RPTR_n_140, RPTR_rgraynext[2], rq2_wptr[2]);
  nand RPTR_g104 (RPTR_n_65, RPTR_n_139, RPTR_n_140);
  or RPTR_g105 (RPTR_n_141, wc2, RPTR_rbinnext[2]);
  not gc2 (wc2, RPTR_rbinnext[3]);
  or RPTR_g106 (RPTR_n_142, RPTR_rbinnext[3], wc3);
  not gc3 (wc3, RPTR_rbinnext[2]);
  nand RPTR_g107 (RPTR_rgraynext[2], RPTR_n_141, RPTR_n_142);
  nand RPTR_g108 (RPTR_n_143, RPTR_n_87, rptr[4]);
  or RPTR_g109 (RPTR_n_144, RPTR_n_87, rptr[4]);
  nand RPTR_g110 (RPTR_rbinnext[4], RPTR_n_143, RPTR_n_144);
  nand RPTR_g111 (RPTR_n_118, RPTR_n_115, RPTR_n_116);
  or RPTR_g112 (RPTR_n_145, wc4, rq2_wptr[1]);
  not gc4 (wc4, RPTR_rgraynext[1]);
  or RPTR_g113 (RPTR_n_146, RPTR_rgraynext[1], wc5);
  not gc5 (wc5, rq2_wptr[1]);
  nand RPTR_g114 (RPTR_n_114, RPTR_n_145, RPTR_n_146);
  or RPTR_g115 (RPTR_n_115, RPTR_rgraynext[0], wc6);
  not gc6 (wc6, rq2_wptr[0]);
  or RPTR_g116 (RPTR_n_116, wc7, rq2_wptr[0]);
  not gc7 (wc7, RPTR_rgraynext[0]);
  or RPTR_g117 (RPTR_n_147, wc8, RPTR_rbinnext[1]);
  not gc8 (wc8, RPTR_rbinnext[2]);
  or RPTR_g118 (RPTR_n_148, RPTR_rbinnext[2], wc9);
  not gc9 (wc9, RPTR_rbinnext[1]);
  nand RPTR_g119 (RPTR_rgraynext[1], RPTR_n_147, RPTR_n_148);
  nand RPTR_g120 (RPTR_n_149, RPTR_n_91, raddr[3]);
  or RPTR_g121 (RPTR_n_150, RPTR_n_91, raddr[3]);
  nand RPTR_g122 (RPTR_rbinnext[3], RPTR_n_149, RPTR_n_150);
  nand RPTR_g123 (RPTR_n_151, raddr[2], RPTR_n_85);
  or RPTR_g124 (RPTR_n_152, raddr[2], RPTR_n_85);
  nand RPTR_g125 (RPTR_rbinnext[2], RPTR_n_151, RPTR_n_152);
  or RPTR_g126 (RPTR_n_153, wc10, RPTR_rbinnext[0]);
  not gc10 (wc10, RPTR_rbinnext[1]);
  or RPTR_g127 (RPTR_n_154, RPTR_rbinnext[1], wc11);
  not gc11 (wc11, RPTR_rbinnext[0]);
  nand RPTR_g128 (RPTR_rgraynext[0], RPTR_n_153, RPTR_n_154);
  or RPTR_g129 (RPTR_n_91, wc12, RPTR_n_85);
  not gc12 (wc12, raddr[2]);
  or RPTR_g130 (RPTR_n_85, RPTR_n_89, wc13);
  not gc13 (wc13, raddr[1]);
  nand RPTR_g131 (RPTR_n_155, RPTR_n_89, raddr[1]);
  or RPTR_g132 (RPTR_n_156, RPTR_n_89, raddr[1]);
  nand RPTR_g133 (RPTR_rbinnext[1], RPTR_n_155, RPTR_n_156);
  nand RPTR_g134 (RPTR_n_157, raddr[0], RPTR_n_29);
  or RPTR_g135 (RPTR_n_158, raddr[0], RPTR_n_29);
  nand RPTR_g136 (RPTR_rbinnext[0], RPTR_n_157, RPTR_n_158);
  or RPTR_g137 (RPTR_n_89, wc14, RPTR_n_29);
  not gc14 (wc14, raddr[0]);
  or RPTR_g138 (RPTR_n_29, wc15, rempty);
  not gc15 (wc15, rinc);
  and RPTR_g139 (RPTR_rempty_val, RPTR_n_92, wc16);
  not gc16 (wc16, RPTR_n_68);
  CDN_flop \RPTR_rbin_reg[0] (.clk (rclk), .d (RPTR_rbinnext[0]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (raddr[0]));
  CDN_flop \RPTR_rbin_reg[1] (.clk (rclk), .d (RPTR_rbinnext[1]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (raddr[1]));
  CDN_flop \RPTR_rbin_reg[2] (.clk (rclk), .d (RPTR_rbinnext[2]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (raddr[2]));
  CDN_flop \RPTR_rbin_reg[3] (.clk (rclk), .d (RPTR_rbinnext[3]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (raddr[3]));
  CDN_flop \RPTR_rbin_reg[4] (.clk (rclk), .d (RPTR_rbinnext[4]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rptr[4]));
  CDN_flop RPTR_rempty_reg(.clk (rclk), .d (RPTR_rempty_val), .sena
       (1'b1), .aclr (1'b0), .apre (W2R_n_49), .srl (1'b0), .srd
       (1'b0), .q (rempty));
  CDN_flop \RPTR_rptr_reg[0] (.clk (rclk), .d (RPTR_rgraynext[0]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rptr[0]));
  CDN_flop \RPTR_rptr_reg[1] (.clk (rclk), .d (RPTR_rgraynext[1]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rptr[1]));
  CDN_flop \RPTR_rptr_reg[2] (.clk (rclk), .d (RPTR_rgraynext[2]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rptr[2]));
  CDN_flop \RPTR_rptr_reg[3] (.clk (rclk), .d (RPTR_rgraynext[3]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rptr[3]));
  not W2R_g1 (W2R_n_49, rrst_n);
  CDN_flop \W2R_rq1_wptr_reg[0] (.clk (rclk), .d (wptr[0]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (W2R_rq1_wptr[0]));
  CDN_flop \W2R_rq1_wptr_reg[1] (.clk (rclk), .d (wptr[1]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (W2R_rq1_wptr[1]));
  CDN_flop \W2R_rq1_wptr_reg[2] (.clk (rclk), .d (wptr[2]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (W2R_rq1_wptr[2]));
  CDN_flop \W2R_rq1_wptr_reg[3] (.clk (rclk), .d (wptr[3]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (W2R_rq1_wptr[3]));
  CDN_flop \W2R_rq1_wptr_reg[4] (.clk (rclk), .d (wptr[4]), .sena
       (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (W2R_rq1_wptr[4]));
  CDN_flop \W2R_rq2_wptr_reg[0] (.clk (rclk), .d (W2R_rq1_wptr[0]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rq2_wptr[0]));
  CDN_flop \W2R_rq2_wptr_reg[1] (.clk (rclk), .d (W2R_rq1_wptr[1]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rq2_wptr[1]));
  CDN_flop \W2R_rq2_wptr_reg[2] (.clk (rclk), .d (W2R_rq1_wptr[2]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rq2_wptr[2]));
  CDN_flop \W2R_rq2_wptr_reg[3] (.clk (rclk), .d (W2R_rq1_wptr[3]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rq2_wptr[3]));
  CDN_flop \W2R_rq2_wptr_reg[4] (.clk (rclk), .d (W2R_rq1_wptr[4]),
       .sena (1'b1), .aclr (W2R_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (rq2_wptr[4]));
  or WPTR_g55 (WPTR_n_89, WPTR_n_93, wc17);
  not gc17 (wc17, waddr[3]);
  or WPTR_g73 (WPTR_n_70, WPTR_n_115, WPTR_n_116);
  or WPTR_g97 (WPTR_n_115, WPTR_n_119, WPTR_n_120);
  nand WPTR_g98 (WPTR_n_119, WPTR_n_67, WPTR_n_68);
  or WPTR_g99 (WPTR_n_135, wc18, wq2_rptr[3]);
  not gc18 (wc18, WPTR_wgraynext[3]);
  or WPTR_g100 (WPTR_n_136, WPTR_wgraynext[3], wc19);
  not gc19 (wc19, wq2_rptr[3]);
  nand WPTR_g101 (WPTR_n_68, WPTR_n_135, WPTR_n_136);
  or WPTR_g102 (WPTR_n_137, wc20, WPTR_wbinnext[3]);
  not gc20 (wc20, WPTR_wbinnext[4]);
  or WPTR_g103 (WPTR_n_138, WPTR_wbinnext[4], wc21);
  not gc21 (wc21, WPTR_wbinnext[3]);
  nand WPTR_g104 (WPTR_wgraynext[3], WPTR_n_137, WPTR_n_138);
  or WPTR_g105 (WPTR_n_139, wc22, wq2_rptr[4]);
  not gc22 (wc22, WPTR_wbinnext[4]);
  or WPTR_g106 (WPTR_n_140, WPTR_wbinnext[4], wc23);
  not gc23 (wc23, wq2_rptr[4]);
  nand WPTR_g107 (WPTR_n_94, WPTR_n_139, WPTR_n_140);
  nand WPTR_g108 (WPTR_n_141, WPTR_wgraynext[2], wq2_rptr[2]);
  or WPTR_g109 (WPTR_n_142, WPTR_wgraynext[2], wq2_rptr[2]);
  nand WPTR_g110 (WPTR_n_67, WPTR_n_141, WPTR_n_142);
  or WPTR_g111 (WPTR_n_143, wc24, WPTR_wbinnext[2]);
  not gc24 (wc24, WPTR_wbinnext[3]);
  or WPTR_g112 (WPTR_n_144, WPTR_wbinnext[3], wc25);
  not gc25 (wc25, WPTR_wbinnext[2]);
  nand WPTR_g113 (WPTR_wgraynext[2], WPTR_n_143, WPTR_n_144);
  nand WPTR_g114 (WPTR_n_145, WPTR_n_89, wptr[4]);
  or WPTR_g115 (WPTR_n_146, WPTR_n_89, wptr[4]);
  nand WPTR_g116 (WPTR_wbinnext[4], WPTR_n_145, WPTR_n_146);
  nand WPTR_g117 (WPTR_n_120, WPTR_n_117, WPTR_n_118);
  or WPTR_g118 (WPTR_n_147, wc26, wq2_rptr[1]);
  not gc26 (wc26, WPTR_wgraynext[1]);
  or WPTR_g119 (WPTR_n_148, WPTR_wgraynext[1], wc27);
  not gc27 (wc27, wq2_rptr[1]);
  nand WPTR_g120 (WPTR_n_116, WPTR_n_147, WPTR_n_148);
  or WPTR_g121 (WPTR_n_117, WPTR_wgraynext[0], wc28);
  not gc28 (wc28, wq2_rptr[0]);
  or WPTR_g122 (WPTR_n_118, wc29, wq2_rptr[0]);
  not gc29 (wc29, WPTR_wgraynext[0]);
  or WPTR_g123 (WPTR_n_149, wc30, WPTR_wbinnext[1]);
  not gc30 (wc30, WPTR_wbinnext[2]);
  or WPTR_g124 (WPTR_n_150, WPTR_wbinnext[2], wc31);
  not gc31 (wc31, WPTR_wbinnext[1]);
  nand WPTR_g125 (WPTR_wgraynext[1], WPTR_n_149, WPTR_n_150);
  nand WPTR_g126 (WPTR_n_151, WPTR_n_93, waddr[3]);
  or WPTR_g127 (WPTR_n_152, WPTR_n_93, waddr[3]);
  nand WPTR_g128 (WPTR_wbinnext[3], WPTR_n_151, WPTR_n_152);
  nand WPTR_g129 (WPTR_n_153, waddr[2], WPTR_n_87);
  or WPTR_g130 (WPTR_n_154, waddr[2], WPTR_n_87);
  nand WPTR_g131 (WPTR_wbinnext[2], WPTR_n_153, WPTR_n_154);
  or WPTR_g132 (WPTR_n_155, wc32, WPTR_wbinnext[0]);
  not gc32 (wc32, WPTR_wbinnext[1]);
  or WPTR_g133 (WPTR_n_156, WPTR_wbinnext[1], wc33);
  not gc33 (wc33, WPTR_wbinnext[0]);
  nand WPTR_g134 (WPTR_wgraynext[0], WPTR_n_155, WPTR_n_156);
  or WPTR_g135 (WPTR_n_93, wc34, WPTR_n_87);
  not gc34 (wc34, waddr[2]);
  or WPTR_g136 (WPTR_n_87, WPTR_n_91, wc35);
  not gc35 (wc35, waddr[1]);
  nand WPTR_g137 (WPTR_n_157, WPTR_n_91, waddr[1]);
  or WPTR_g138 (WPTR_n_158, WPTR_n_91, waddr[1]);
  nand WPTR_g139 (WPTR_wbinnext[1], WPTR_n_157, WPTR_n_158);
  nand WPTR_g140 (WPTR_n_159, waddr[0], WPTR_n_31);
  or WPTR_g141 (WPTR_n_160, waddr[0], WPTR_n_31);
  nand WPTR_g142 (WPTR_wbinnext[0], WPTR_n_159, WPTR_n_160);
  or WPTR_g143 (WPTR_n_91, wc36, WPTR_n_31);
  not gc36 (wc36, waddr[0]);
  and WPTR_g145 (WPTR_wfull_val, WPTR_n_94, wc37);
  not gc37 (wc37, WPTR_n_70);
  CDN_flop \WPTR_wbin_reg[0] (.clk (wclk), .d (WPTR_wbinnext[0]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (waddr[0]));
  CDN_flop \WPTR_wbin_reg[1] (.clk (wclk), .d (WPTR_wbinnext[1]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (waddr[1]));
  CDN_flop \WPTR_wbin_reg[2] (.clk (wclk), .d (WPTR_wbinnext[2]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (waddr[2]));
  CDN_flop \WPTR_wbin_reg[3] (.clk (wclk), .d (WPTR_wbinnext[3]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (waddr[3]));
  CDN_flop \WPTR_wbin_reg[4] (.clk (wclk), .d (WPTR_wbinnext[4]), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wptr[4]));
  CDN_flop WPTR_wfull_reg(.clk (wclk), .d (WPTR_wfull_val), .sena
       (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wfull));
  CDN_flop \WPTR_wptr_reg[0] (.clk (wclk), .d (WPTR_wgraynext[0]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wptr[0]));
  CDN_flop \WPTR_wptr_reg[1] (.clk (wclk), .d (WPTR_wgraynext[1]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wptr[1]));
  CDN_flop \WPTR_wptr_reg[2] (.clk (wclk), .d (WPTR_wgraynext[2]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wptr[2]));
  CDN_flop \WPTR_wptr_reg[3] (.clk (wclk), .d (WPTR_wgraynext[3]),
       .sena (1'b1), .aclr (R2W_n_49), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (wptr[3]));
  nand g1215 (rdata[5], n_1138, n_1139);
  nand g1216 (rdata[3], n_1150, n_1151);
  nand g1217 (rdata[7], n_1126, n_1127);
  nand g1218 (rdata[1], n_1162, n_1163);
  nand g1219 (rdata[4], n_1144, n_1145);
  nand g1220 (rdata[6], n_1132, n_1133);
  nand g1221 (rdata[0], n_1168, n_1169);
  nand g1222 (rdata[2], n_1156, n_1157);
  nand g1223 (n_1169, n_411, raddr[3]);
  nand g1224 (n_1127, n_397, raddr[3]);
  or g1225 (n_1132, wc38, raddr[3]);
  not gc38 (wc38, n_400);
  nand g1226 (n_1133, n_399, raddr[3]);
  or g1227 (n_1138, wc39, raddr[3]);
  not gc39 (wc39, n_402);
  nand g1228 (n_1139, n_401, raddr[3]);
  or g1229 (n_1144, wc40, raddr[3]);
  not gc40 (wc40, n_404);
  nand g1230 (n_1145, n_403, raddr[3]);
  or g1231 (n_1150, wc41, raddr[3]);
  not gc41 (wc41, n_406);
  nand g1232 (n_1151, n_405, raddr[3]);
  or g1233 (n_1156, wc42, raddr[3]);
  not gc42 (wc42, n_408);
  nand g1234 (n_1157, n_407, raddr[3]);
  or g1235 (n_1162, wc43, raddr[3]);
  not gc43 (wc43, n_410);
  nand g1236 (n_1163, n_409, raddr[3]);
  or g1237 (n_1168, wc44, raddr[3]);
  not gc44 (wc44, n_412);
  or g1238 (n_1126, wc45, raddr[3]);
  not gc45 (wc45, n_398);
  or g1239 (n_412, n_1072, n_1073);
  or g1240 (n_408, n_904, n_905);
  or g1241 (n_405, n_862, n_863);
  or g1242 (n_409, n_1030, n_1031);
  or g1243 (n_399, n_610, n_611);
  or g1244 (n_403, n_778, n_779);
  or g1245 (n_407, n_946, n_947);
  or g1246 (n_406, n_820, n_821);
  or g1247 (n_410, n_988, n_989);
  or g1248 (n_404, n_736, n_737);
  or g1249 (n_402, n_652, n_653);
  or g1250 (n_401, n_694, n_695);
  or g1251 (n_397, n_526, n_527);
  or g1252 (n_400, n_568, n_569);
  or g1253 (n_398, n_484, n_485);
  or g1254 (n_411, n_1114, n_1115);
  or g1255 (n_820, n_816, n_817);
  or g1256 (n_862, n_858, n_859);
  or g1261 (n_863, n_860, n_861);
  or g1266 (n_779, n_776, n_777);
  or g1271 (n_778, n_774, n_775);
  or g1276 (n_737, n_734, n_735);
  or g1281 (n_904, n_900, n_901);
  or g1286 (n_905, n_902, n_903);
  or g1291 (n_736, n_732, n_733);
  or g1296 (n_695, n_692, n_693);
  or g1297 (n_694, n_690, n_691);
  or g1298 (n_946, n_942, n_943);
  or g1299 (n_947, n_944, n_945);
  or g1300 (n_484, n_480, n_481);
  or g1301 (n_485, n_482, n_483);
  or g1302 (n_1115, n_1112, n_1113);
  or g1303 (n_1114, n_1110, n_1111);
  or g1304 (n_653, n_650, n_651);
  or g1305 (n_652, n_648, n_649);
  or g1306 (n_988, n_984, n_985);
  or g1307 (n_989, n_986, n_987);
  or g1308 (n_611, n_608, n_609);
  or g1309 (n_610, n_606, n_607);
  or g1310 (n_821, n_818, n_819);
  or g1311 (n_1030, n_1026, n_1027);
  or g1312 (n_526, n_522, n_523);
  or g1313 (n_527, n_524, n_525);
  or g1314 (n_1031, n_1028, n_1029);
  or g1315 (n_1073, n_1070, n_1071);
  or g1316 (n_1072, n_1068, n_1069);
  or g1317 (n_569, n_566, n_567);
  or g1318 (n_568, n_564, n_565);
  nand g1319 (n_1068, n_1060, n_1061);
  nand g1320 (n_565, n_558, n_559);
  nand g1321 (n_566, n_560, n_561);
  nand g1322 (n_567, n_562, n_563);
  nand g1323 (n_1069, n_1062, n_1063);
  nand g1324 (n_1070, n_1064, n_1065);
  nand g1325 (n_606, n_598, n_599);
  nand g1326 (n_607, n_600, n_601);
  nand g1327 (n_1071, n_1066, n_1067);
  nand g1328 (n_564, n_556, n_557);
  nand g1329 (n_1029, n_1024, n_1025);
  nand g1330 (n_525, n_520, n_521);
  nand g1331 (n_1027, n_1020, n_1021);
  nand g1332 (n_1026, n_1018, n_1019);
  nand g1333 (n_608, n_602, n_603);
  nand g1334 (n_609, n_604, n_605);
  nand g1335 (n_524, n_518, n_519);
  nand g1336 (n_523, n_516, n_517);
  nand g1337 (n_648, n_640, n_641);
  nand g1338 (n_649, n_642, n_643);
  nand g1339 (n_650, n_644, n_645);
  nand g1340 (n_522, n_514, n_515);
  nand g1341 (n_1110, n_1102, n_1103);
  nand g1342 (n_987, n_982, n_983);
  nand g1343 (n_986, n_980, n_981);
  nand g1344 (n_985, n_978, n_979);
  nand g1345 (n_984, n_976, n_977);
  nand g1346 (n_651, n_646, n_647);
  nand g1347 (n_1111, n_1104, n_1105);
  nand g1348 (n_1112, n_1106, n_1107);
  nand g1349 (n_690, n_682, n_683);
  nand g1350 (n_691, n_684, n_685);
  nand g1351 (n_692, n_686, n_687);
  nand g1352 (n_693, n_688, n_689);
  nand g1353 (n_1113, n_1108, n_1109);
  nand g1354 (n_483, n_478, n_479);
  nand g1355 (n_945, n_940, n_941);
  nand g1356 (n_944, n_938, n_939);
  nand g1357 (n_943, n_936, n_937);
  nand g1358 (n_942, n_934, n_935);
  nand g1359 (n_482, n_476, n_477);
  nand g1360 (n_481, n_474, n_475);
  nand g1361 (n_732, n_724, n_725);
  nand g1362 (n_733, n_726, n_727);
  nand g1363 (n_734, n_728, n_729);
  nand g1364 (n_735, n_730, n_731);
  nand g1365 (n_480, n_472, n_473);
  or g1366 (n_1193, n_430, waddr[0]);
  or g1367 (n_1190, n_430, wc46);
  not gc46 (wc46, waddr[0]);
  nand g1368 (n_903, n_898, n_899);
  nand g1369 (n_902, n_896, n_897);
  nand g1370 (n_901, n_894, n_895);
  nand g1371 (n_900, n_892, n_893);
  or g1372 (n_1187, n_429, wc47);
  not gc47 (wc47, waddr[0]);
  nand g1373 (n_774, n_766, n_767);
  nand g1374 (n_775, n_768, n_769);
  nand g1375 (n_776, n_770, n_771);
  nand g1376 (n_777, n_772, n_773);
  or g1377 (n_1184, n_429, waddr[0]);
  or g1378 (n_1181, n_428, wc48);
  not gc48 (wc48, waddr[1]);
  or g1379 (n_1178, n_428, waddr[1]);
  or g1380 (n_1175, n_427, waddr[1]);
  nand g1381 (n_861, n_856, n_857);
  nand g1382 (n_860, n_854, n_855);
  nand g1383 (n_859, n_852, n_853);
  nand g1384 (n_858, n_850, n_851);
  nand g1385 (n_816, n_808, n_809);
  nand g1386 (n_817, n_810, n_811);
  nand g1387 (n_818, n_812, n_813);
  nand g1388 (n_819, n_814, n_815);
  or g1389 (n_1172, n_427, wc49);
  not gc49 (wc49, waddr[1]);
  nand g1390 (n_1028, n_1022, n_1023);
  or g1391 (n_850, n_424, wc50);
  not gc50 (wc50, \MEM_memo[9] [3]);
  or g1392 (n_851, n_423, wc51);
  not gc51 (wc51, \MEM_memo[15] [3]);
  or g1393 (n_852, n_422, wc52);
  not gc52 (wc52, \MEM_memo[14] [3]);
  or g1394 (n_853, n_421, wc53);
  not gc53 (wc53, \MEM_memo[12] [3]);
  or g1395 (n_473, n_423, wc54);
  not gc54 (wc54, \MEM_memo[7] [7]);
  or g1396 (n_855, n_419, wc55);
  not gc55 (wc55, \MEM_memo[10] [3]);
  or g1397 (n_815, n_417, wc56);
  not gc56 (wc56, \MEM_memo[3] [3]);
  or g1398 (n_814, n_418, wc57);
  not gc57 (wc57, \MEM_memo[5] [3]);
  or g1399 (n_813, n_419, wc58);
  not gc58 (wc58, \MEM_memo[2] [3]);
  or g1400 (n_812, n_420, wc59);
  not gc59 (wc59, \MEM_memo[0] [3]);
  or g1401 (n_811, n_421, wc60);
  not gc60 (wc60, \MEM_memo[4] [3]);
  or g1402 (n_810, n_422, wc61);
  not gc61 (wc61, \MEM_memo[6] [3]);
  or g1403 (n_809, n_423, wc62);
  not gc62 (wc62, \MEM_memo[7] [3]);
  or g1404 (n_808, n_424, wc63);
  not gc63 (wc63, \MEM_memo[1] [3]);
  or g1405 (n_856, n_418, wc64);
  not gc64 (wc64, \MEM_memo[13] [3]);
  or g1406 (n_857, n_417, wc65);
  not gc65 (wc65, \MEM_memo[11] [3]);
  or g1407 (n_892, n_424, wc66);
  not gc66 (wc66, \MEM_memo[1] [2]);
  or g1408 (n_893, n_423, wc67);
  not gc67 (wc67, \MEM_memo[7] [2]);
  or g1409 (n_894, n_422, wc68);
  not gc68 (wc68, \MEM_memo[6] [2]);
  or g1410 (n_895, n_421, wc69);
  not gc69 (wc69, \MEM_memo[4] [2]);
  or g1411 (n_896, n_420, wc70);
  not gc70 (wc70, \MEM_memo[0] [2]);
  or g1412 (n_773, n_417, wc71);
  not gc71 (wc71, \MEM_memo[11] [4]);
  or g1413 (n_772, n_418, wc72);
  not gc72 (wc72, \MEM_memo[13] [4]);
  or g1414 (n_771, n_419, wc73);
  not gc73 (wc73, \MEM_memo[10] [4]);
  or g1415 (n_770, n_420, wc74);
  not gc74 (wc74, \MEM_memo[8] [4]);
  or g1416 (n_769, n_421, wc75);
  not gc75 (wc75, \MEM_memo[12] [4]);
  or g1417 (n_768, n_422, wc76);
  not gc76 (wc76, \MEM_memo[14] [4]);
  or g1418 (n_767, n_423, wc77);
  not gc77 (wc77, \MEM_memo[15] [4]);
  or g1419 (n_766, n_424, wc78);
  not gc78 (wc78, \MEM_memo[9] [4]);
  or g1420 (n_897, n_419, wc79);
  not gc79 (wc79, \MEM_memo[2] [2]);
  or g1421 (n_898, n_418, wc80);
  not gc80 (wc80, \MEM_memo[5] [2]);
  or g1422 (n_899, n_417, wc81);
  not gc81 (wc81, \MEM_memo[3] [2]);
  or g1423 (n_934, n_424, wc82);
  not gc82 (wc82, \MEM_memo[9] [2]);
  or g1424 (n_935, n_423, wc83);
  not gc83 (wc83, \MEM_memo[15] [2]);
  or g1425 (n_936, n_422, wc84);
  not gc84 (wc84, \MEM_memo[14] [2]);
  or g1426 (n_937, n_421, wc85);
  not gc85 (wc85, \MEM_memo[12] [2]);
  or g1427 (n_731, n_417, wc86);
  not gc86 (wc86, \MEM_memo[3] [4]);
  or g1428 (n_730, n_418, wc87);
  not gc87 (wc87, \MEM_memo[5] [4]);
  or g1429 (n_729, n_419, wc88);
  not gc88 (wc88, \MEM_memo[2] [4]);
  or g1430 (n_728, n_420, wc89);
  not gc89 (wc89, \MEM_memo[0] [4]);
  or g1431 (n_727, n_421, wc90);
  not gc90 (wc90, \MEM_memo[4] [4]);
  or g1432 (n_726, n_422, wc91);
  not gc91 (wc91, \MEM_memo[6] [4]);
  or g1433 (n_725, n_423, wc92);
  not gc92 (wc92, \MEM_memo[7] [4]);
  or g1434 (n_724, n_424, wc93);
  not gc93 (wc93, \MEM_memo[1] [4]);
  or g1435 (n_938, n_420, wc94);
  not gc94 (wc94, \MEM_memo[8] [2]);
  or g1436 (n_939, n_419, wc95);
  not gc95 (wc95, \MEM_memo[10] [2]);
  or g1437 (n_940, n_418, wc96);
  not gc96 (wc96, \MEM_memo[13] [2]);
  or g1438 (n_941, n_417, wc97);
  not gc97 (wc97, \MEM_memo[11] [2]);
  or g1439 (n_976, n_424, wc98);
  not gc98 (wc98, \MEM_memo[1] [1]);
  or g1440 (n_977, n_423, wc99);
  not gc99 (wc99, \MEM_memo[7] [1]);
  or g1441 (n_978, n_422, wc100);
  not gc100 (wc100, \MEM_memo[6] [1]);
  or g1442 (n_689, n_417, wc101);
  not gc101 (wc101, \MEM_memo[11] [5]);
  or g1443 (n_688, n_418, wc102);
  not gc102 (wc102, \MEM_memo[13] [5]);
  or g1444 (n_687, n_419, wc103);
  not gc103 (wc103, \MEM_memo[10] [5]);
  or g1445 (n_686, n_420, wc104);
  not gc104 (wc104, \MEM_memo[8] [5]);
  or g1446 (n_685, n_421, wc105);
  not gc105 (wc105, \MEM_memo[12] [5]);
  or g1447 (n_684, n_422, wc106);
  not gc106 (wc106, \MEM_memo[14] [5]);
  or g1448 (n_683, n_423, wc107);
  not gc107 (wc107, \MEM_memo[15] [5]);
  or g1449 (n_682, n_424, wc108);
  not gc108 (wc108, \MEM_memo[9] [5]);
  or g1450 (n_979, n_421, wc109);
  not gc109 (wc109, \MEM_memo[4] [1]);
  or g1451 (n_980, n_420, wc110);
  not gc110 (wc110, \MEM_memo[0] [1]);
  or g1452 (n_981, n_419, wc111);
  not gc111 (wc111, \MEM_memo[2] [1]);
  or g1453 (n_982, n_418, wc112);
  not gc112 (wc112, \MEM_memo[5] [1]);
  or g1454 (n_983, n_417, wc113);
  not gc113 (wc113, \MEM_memo[3] [1]);
  or g1455 (n_1018, n_424, wc114);
  not gc114 (wc114, \MEM_memo[9] [1]);
  or g1456 (n_1019, n_423, wc115);
  not gc115 (wc115, \MEM_memo[15] [1]);
  or g1457 (n_647, n_417, wc116);
  not gc116 (wc116, \MEM_memo[3] [5]);
  or g1458 (n_646, n_418, wc117);
  not gc117 (wc117, \MEM_memo[5] [5]);
  or g1459 (n_645, n_419, wc118);
  not gc118 (wc118, \MEM_memo[2] [5]);
  or g1460 (n_644, n_420, wc119);
  not gc119 (wc119, \MEM_memo[0] [5]);
  or g1461 (n_643, n_421, wc120);
  not gc120 (wc120, \MEM_memo[4] [5]);
  or g1462 (n_642, n_422, wc121);
  not gc121 (wc121, \MEM_memo[6] [5]);
  or g1463 (n_641, n_423, wc122);
  not gc122 (wc122, \MEM_memo[7] [5]);
  or g1464 (n_640, n_424, wc123);
  not gc123 (wc123, \MEM_memo[1] [5]);
  or g1465 (n_1020, n_422, wc124);
  not gc124 (wc124, \MEM_memo[14] [1]);
  or g1466 (n_1021, n_421, wc125);
  not gc125 (wc125, \MEM_memo[12] [1]);
  or g1467 (n_1022, n_420, wc126);
  not gc126 (wc126, \MEM_memo[8] [1]);
  or g1468 (n_1023, n_419, wc127);
  not gc127 (wc127, \MEM_memo[10] [1]);
  or g1469 (n_1024, n_418, wc128);
  not gc128 (wc128, \MEM_memo[13] [1]);
  or g1470 (n_1025, n_417, wc129);
  not gc129 (wc129, \MEM_memo[11] [1]);
  or g1471 (n_1060, n_424, wc130);
  not gc130 (wc130, \MEM_memo[1] [0]);
  or g1472 (n_605, n_417, wc131);
  not gc131 (wc131, \MEM_memo[11] [6]);
  or g1473 (n_604, n_418, wc132);
  not gc132 (wc132, \MEM_memo[13] [6]);
  or g1474 (n_603, n_419, wc133);
  not gc133 (wc133, \MEM_memo[10] [6]);
  or g1475 (n_602, n_420, wc134);
  not gc134 (wc134, \MEM_memo[8] [6]);
  or g1476 (n_601, n_421, wc135);
  not gc135 (wc135, \MEM_memo[12] [6]);
  or g1477 (n_600, n_422, wc136);
  not gc136 (wc136, \MEM_memo[14] [6]);
  or g1478 (n_599, n_423, wc137);
  not gc137 (wc137, \MEM_memo[15] [6]);
  or g1479 (n_598, n_424, wc138);
  not gc138 (wc138, \MEM_memo[9] [6]);
  or g1480 (n_1061, n_423, wc139);
  not gc139 (wc139, \MEM_memo[7] [0]);
  or g1481 (n_1062, n_422, wc140);
  not gc140 (wc140, \MEM_memo[6] [0]);
  or g1482 (n_1063, n_421, wc141);
  not gc141 (wc141, \MEM_memo[4] [0]);
  or g1483 (n_1064, n_420, wc142);
  not gc142 (wc142, \MEM_memo[0] [0]);
  or g1484 (n_1065, n_419, wc143);
  not gc143 (wc143, \MEM_memo[2] [0]);
  or g1485 (n_1066, n_418, wc144);
  not gc144 (wc144, \MEM_memo[5] [0]);
  or g1486 (n_1067, n_417, wc145);
  not gc145 (wc145, \MEM_memo[3] [0]);
  or g1487 (n_563, n_417, wc146);
  not gc146 (wc146, \MEM_memo[3] [6]);
  or g1488 (n_562, n_418, wc147);
  not gc147 (wc147, \MEM_memo[5] [6]);
  or g1489 (n_561, n_419, wc148);
  not gc148 (wc148, \MEM_memo[2] [6]);
  or g1490 (n_560, n_420, wc149);
  not gc149 (wc149, \MEM_memo[0] [6]);
  or g1491 (n_559, n_421, wc150);
  not gc150 (wc150, \MEM_memo[4] [6]);
  or g1492 (n_558, n_422, wc151);
  not gc151 (wc151, \MEM_memo[6] [6]);
  or g1493 (n_557, n_423, wc152);
  not gc152 (wc152, \MEM_memo[7] [6]);
  or g1494 (n_556, n_424, wc153);
  not gc153 (wc153, \MEM_memo[1] [6]);
  or g1495 (n_1102, n_424, wc154);
  not gc154 (wc154, \MEM_memo[9] [0]);
  or g1496 (n_1103, n_423, wc155);
  not gc155 (wc155, \MEM_memo[15] [0]);
  or g1497 (n_1104, n_422, wc156);
  not gc156 (wc156, \MEM_memo[14] [0]);
  or g1498 (n_1105, n_421, wc157);
  not gc157 (wc157, \MEM_memo[12] [0]);
  or g1499 (n_1106, n_420, wc158);
  not gc158 (wc158, \MEM_memo[8] [0]);
  or g1500 (n_1107, n_419, wc159);
  not gc159 (wc159, \MEM_memo[10] [0]);
  or g1501 (n_1108, n_418, wc160);
  not gc160 (wc160, \MEM_memo[13] [0]);
  or g1502 (n_521, n_417, wc161);
  not gc161 (wc161, \MEM_memo[11] [7]);
  or g1503 (n_520, n_418, wc162);
  not gc162 (wc162, \MEM_memo[13] [7]);
  or g1504 (n_519, n_419, wc163);
  not gc163 (wc163, \MEM_memo[10] [7]);
  or g1505 (n_518, n_420, wc164);
  not gc164 (wc164, \MEM_memo[8] [7]);
  or g1506 (n_517, n_421, wc165);
  not gc165 (wc165, \MEM_memo[12] [7]);
  or g1507 (n_516, n_422, wc166);
  not gc166 (wc166, \MEM_memo[14] [7]);
  or g1508 (n_515, n_423, wc167);
  not gc167 (wc167, \MEM_memo[15] [7]);
  or g1509 (n_514, n_424, wc168);
  not gc168 (wc168, \MEM_memo[9] [7]);
  or g1510 (n_1109, n_417, wc169);
  not gc169 (wc169, \MEM_memo[11] [0]);
  or g1511 (n_472, n_424, wc170);
  not gc170 (wc170, \MEM_memo[1] [7]);
  or g1512 (n_427, n_1118, waddr[0]);
  or g1513 (n_428, n_1118, wc171);
  not gc171 (wc171, waddr[0]);
  or g1514 (n_854, n_420, wc172);
  not gc172 (wc172, \MEM_memo[8] [3]);
  or g1515 (n_429, n_1121, waddr[1]);
  or g1516 (n_430, n_1121, wc173);
  not gc173 (wc173, waddr[1]);
  or g1517 (n_479, n_417, wc174);
  not gc174 (wc174, \MEM_memo[3] [7]);
  or g1518 (n_478, n_418, wc175);
  not gc175 (wc175, \MEM_memo[5] [7]);
  or g1519 (n_477, n_419, wc176);
  not gc176 (wc176, \MEM_memo[2] [7]);
  or g1520 (n_476, n_420, wc177);
  not gc177 (wc177, \MEM_memo[0] [7]);
  or g1521 (n_475, n_421, wc178);
  not gc178 (wc178, \MEM_memo[4] [7]);
  or g1522 (n_474, n_422, wc179);
  not gc179 (wc179, \MEM_memo[6] [7]);
  or g1523 (n_424, n_434, wc180);
  not gc180 (wc180, raddr[0]);
  or g1524 (n_420, n_434, raddr[0]);
  or g1525 (n_1118, WPTR_n_31, wc181);
  not gc181 (wc181, waddr[3]);
  or g1526 (n_1121, WPTR_n_31, waddr[3]);
  or g1527 (n_417, n_443, wc182);
  not gc182 (wc182, raddr[0]);
  or g1528 (n_419, n_443, raddr[0]);
  or g1529 (n_418, n_437, wc183);
  not gc183 (wc183, raddr[0]);
  or g1530 (n_422, n_440, raddr[0]);
  or g1531 (n_423, n_440, wc184);
  not gc184 (wc184, raddr[0]);
  or g1532 (n_421, n_437, raddr[0]);
  nand g1533 (n_440, raddr[2], raddr[1]);
  or g1534 (n_437, wc185, raddr[1]);
  not gc185 (wc185, raddr[2]);
  or g1535 (n_443, raddr[2], wc186);
  not gc186 (wc186, raddr[1]);
  or g1536 (n_434, raddr[2], raddr[1]);
  or g1537 (WPTR_n_31, wc187, wfull);
  not gc187 (wc187, winc);
  nor g1538 (MEM_n_370, n_1172, waddr[2]);
  and g1539 (MEM_n_374, waddr[2], wc188);
  not gc188 (wc188, n_1172);
  and g1540 (MEM_n_372, waddr[2], wc189);
  not gc189 (wc189, n_1175);
  nor g1541 (MEM_n_368, n_1175, waddr[2]);
  and g1542 (MEM_n_373, waddr[2], wc190);
  not gc190 (wc190, n_1178);
  nor g1543 (MEM_n_369, n_1178, waddr[2]);
  nor g1544 (MEM_n_371, n_1181, waddr[2]);
  and g1545 (MEM_n_375, waddr[2], wc191);
  not gc191 (wc191, n_1181);
  and g1546 (MEM_n_364, waddr[2], wc192);
  not gc192 (wc192, n_1184);
  nor g1547 (MEM_n_360, n_1184, waddr[2]);
  and g1548 (MEM_n_365, waddr[2], wc193);
  not gc193 (wc193, n_1187);
  nor g1549 (MEM_n_361, n_1187, waddr[2]);
  nor g1550 (MEM_n_363, n_1190, waddr[2]);
  and g1551 (MEM_n_367, waddr[2], wc194);
  not gc194 (wc194, n_1190);
  and g1552 (MEM_n_366, waddr[2], wc195);
  not gc195 (wc195, n_1193);
  nor g1553 (MEM_n_362, n_1193, waddr[2]);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
