
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May  8 2023 18:49:30 IST (May  8 2023 13:19:30 UTC)

// Verification Directory fv/async_fifo1 

module async_fifo1(winc, wclk, wrst_n, rinc, rclk, rrst_n, wdata,
     rdata, wfull, rempty);
  input winc, wclk, wrst_n, rinc, rclk, rrst_n;
  input [7:0] wdata;
  output [7:0] rdata;
  output wfull, rempty;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n;
  wire [7:0] wdata;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [4:0] wq2_rptr;
  wire [4:0] rq2_wptr;
  wire [4:0] W2R_rq1_wptr;
  wire [4:0] R2W_wq1_rptr;
  wire [4:0] wptr;
  wire [4:0] rptr;
  wire [3:0] raddr;
  wire [7:0] \MEM_memo[9] ;
  wire [7:0] \MEM_memo[13] ;
  wire [7:0] \MEM_memo[12] ;
  wire [7:0] \MEM_memo[14] ;
  wire [7:0] \MEM_memo[3] ;
  wire [7:0] \MEM_memo[5] ;
  wire [7:0] \MEM_memo[15] ;
  wire [7:0] \MEM_memo[1] ;
  wire [7:0] \MEM_memo[7] ;
  wire [7:0] \MEM_memo[8] ;
  wire [7:0] \MEM_memo[10] ;
  wire [7:0] \MEM_memo[11] ;
  wire [3:0] waddr;
  wire [7:0] \MEM_memo[6] ;
  wire [7:0] \MEM_memo[2] ;
  wire [7:0] \MEM_memo[4] ;
  wire [7:0] \MEM_memo[0] ;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_237, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253;
  DFFSHQX4 RPTR_rempty_reg(.SN (rrst_n), .CK (rclk), .D (n_253), .Q
       (rempty));
  DFFRHQX4 WPTR_wfull_reg(.RN (wrst_n), .CK (wclk), .D (n_252), .Q
       (wfull));
  NOR4BBX2 g4913__2398(.AN (n_246), .BN (n_242), .C (n_226), .D
       (n_251), .Y (n_253));
  NOR4BBX2 g4911__5107(.AN (n_243), .BN (n_206), .C (n_228), .D
       (n_250), .Y (n_252));
  NAND2X2 g4916__6260(.A (n_248), .B (n_249), .Y (n_251));
  OAI221X2 g4914__4319(.A0 (n_198), .A1 (wq2_rptr[1]), .B0 (n_229), .B1
       (n_240), .C0 (n_245), .Y (n_250));
  XNOR3X1 g4920__8428(.A (rq2_wptr[3]), .B (n_247), .C (n_227), .Y
       (n_249));
  XNOR3X1 g4924__5526(.A (rq2_wptr[2]), .B (n_179), .C (n_247), .Y
       (n_248));
  XNOR3X1 g4932__6783(.A (rq2_wptr[1]), .B (n_146), .C (n_219), .Y
       (n_246));
  OAI2BB2X2 g4915__3680(.A0N (n_244), .A1N (wq2_rptr[3]), .B0 (n_244),
       .B1 (wq2_rptr[3]), .Y (n_245));
  MXI2X1 g4917__1617(.A (n_230), .B (n_241), .S0 (wq2_rptr[2]), .Y
       (n_243));
  DFFRXL \W2R_rq2_wptr_reg[2] (.RN (rrst_n), .CK (rclk), .D
       (W2R_rq1_wptr[2]), .Q (UNCONNECTED), .QN (rq2_wptr[2]));
  DFFRXL \W2R_rq2_wptr_reg[3] (.RN (rrst_n), .CK (rclk), .D
       (W2R_rq1_wptr[3]), .Q (UNCONNECTED0), .QN (rq2_wptr[3]));
  DFFRHQX1 \W2R_rq2_wptr_reg[1] (.RN (rrst_n), .CK (rclk), .D
       (W2R_rq1_wptr[1]), .Q (rq2_wptr[1]));
  XNOR3X1 g4938__2802(.A (rq2_wptr[0]), .B (n_85), .C (n_178), .Y
       (n_242));
  DFFRX2 \R2W_wq2_rptr_reg[3] (.RN (wrst_n), .CK (wclk), .D
       (R2W_wq1_rptr[3]), .Q (UNCONNECTED1), .QN (wq2_rptr[3]));
  DFFRHQX2 \W2R_rq1_wptr_reg[2] (.RN (rrst_n), .CK (rclk), .D
       (wptr[2]), .Q (W2R_rq1_wptr[2]));
  DFFRHQX2 \W2R_rq1_wptr_reg[3] (.RN (rrst_n), .CK (rclk), .D
       (wptr[3]), .Q (W2R_rq1_wptr[3]));
  DFFRHQX2 \W2R_rq1_wptr_reg[1] (.RN (rrst_n), .CK (rclk), .D
       (wptr[1]), .Q (W2R_rq1_wptr[1]));
  DFFRHQX2 \R2W_wq1_rptr_reg[3] (.RN (wrst_n), .CK (wclk), .D
       (rptr[3]), .Q (R2W_wq1_rptr[3]));
  DFFRX1 \R2W_wq2_rptr_reg[2] (.RN (wrst_n), .CK (wclk), .D
       (R2W_wq1_rptr[2]), .Q (UNCONNECTED2), .QN (wq2_rptr[2]));
  DFFRHQX1 \WPTR_wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_241), .Q
       (wptr[2]));
  DFFRHQX1 \WPTR_wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_244), .Q
       (wptr[3]));
  DFFRHQX1 \W2R_rq2_wptr_reg[0] (.RN (rrst_n), .CK (rclk), .D
       (W2R_rq1_wptr[0]), .Q (rq2_wptr[0]));
  INVX3 g4930(.A (wq2_rptr[1]), .Y (n_240));
  MXI2XL g5008__1705(.A (n_213), .B (n_217), .S0 (n_237), .Y
       (rdata[7]));
  MXI2XL g5009__5122(.A (n_208), .B (n_204), .S0 (n_237), .Y
       (rdata[6]));
  MXI2XL g5011__8246(.A (n_200), .B (n_209), .S0 (n_237), .Y
       (rdata[5]));
  MXI2XL g5010__7098(.A (n_220), .B (n_203), .S0 (n_237), .Y
       (rdata[4]));
  MXI2XL g5012__6131(.A (n_201), .B (n_199), .S0 (n_237), .Y
       (rdata[3]));
  MXI2XL g5002__1881(.A (n_212), .B (n_216), .S0 (n_237), .Y
       (rdata[2]));
  MXI2XL g5001__5115(.A (n_207), .B (n_205), .S0 (n_237), .Y
       (rdata[1]));
  MXI2XL g5013__7482(.A (n_202), .B (n_193), .S0 (raddr[3]), .Y
       (rdata[0]));
  INVX1 g4955(.A (n_241), .Y (n_230));
  DFFRHQX1 \WPTR_wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_229), .Q
       (wptr[1]));
  DFFRHQX4 \R2W_wq2_rptr_reg[1] (.RN (wrst_n), .CK (wclk), .D
       (R2W_wq1_rptr[1]), .Q (wq2_rptr[1]));
  MXI2X1 g4971__4733(.A (n_194), .B (n_223), .S0 (wq2_rptr[4]), .Y
       (n_228));
  SDFFRHQX2 \RPTR_rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_227),
       .SE (n_218), .SI (n_225), .Q (rptr[3]));
  DFFRHQX2 \R2W_wq1_rptr_reg[2] (.RN (wrst_n), .CK (wclk), .D
       (rptr[2]), .Q (R2W_wq1_rptr[2]));
  MXI2X1 g4925__6161(.A (n_227), .B (n_225), .S0 (rq2_wptr[4]), .Y
       (n_226));
  DFFRHQX2 \W2R_rq1_wptr_reg[0] (.RN (rrst_n), .CK (rclk), .D
       (wptr[0]), .Q (W2R_rq1_wptr[0]));
  SDFFQX2 \MEM_memo_reg[9][4] (.CK (wclk), .D (wdata[4]), .SE (n_224),
       .SI (\MEM_memo[9] [4]), .Q (\MEM_memo[9] [4]));
  SDFFQX2 \MEM_memo_reg[9][1] (.CK (wclk), .D (wdata[1]), .SE (n_224),
       .SI (\MEM_memo[9] [1]), .Q (\MEM_memo[9] [1]));
  SDFFQX2 \MEM_memo_reg[9][2] (.CK (wclk), .D (wdata[2]), .SE (n_224),
       .SI (\MEM_memo[9] [2]), .Q (\MEM_memo[9] [2]));
  SDFFQX2 \MEM_memo_reg[9][3] (.CK (wclk), .D (wdata[3]), .SE (n_224),
       .SI (\MEM_memo[9] [3]), .Q (\MEM_memo[9] [3]));
  SDFFQX2 \MEM_memo_reg[9][7] (.CK (wclk), .D (wdata[7]), .SE (n_224),
       .SI (\MEM_memo[9] [7]), .Q (\MEM_memo[9] [7]));
  SDFFQX2 \MEM_memo_reg[9][5] (.CK (wclk), .D (wdata[5]), .SE (n_224),
       .SI (\MEM_memo[9] [5]), .Q (\MEM_memo[9] [5]));
  OAI2BB2X4 g4964__9315(.A0N (n_222), .A1N (n_223), .B0 (n_222), .B1
       (n_223), .Y (n_244));
  OAI22X2 g4965__9945(.A0 (n_190), .A1 (n_195), .B0 (n_189), .B1
       (n_222), .Y (n_241));
  SDFFHQX4 \MEM_memo_reg[13][0] (.CK (wclk), .D (wdata[0]), .SE
       (n_221), .SI (\MEM_memo[13] [0]), .Q (\MEM_memo[13] [0]));
  SDFFQX2 \MEM_memo_reg[13][1] (.CK (wclk), .D (wdata[1]), .SE (n_221),
       .SI (\MEM_memo[13] [1]), .Q (\MEM_memo[13] [1]));
  SDFFQX2 \MEM_memo_reg[9][0] (.CK (wclk), .D (wdata[0]), .SE (n_224),
       .SI (\MEM_memo[9] [0]), .Q (\MEM_memo[9] [0]));
  SDFFQX2 \MEM_memo_reg[13][3] (.CK (wclk), .D (wdata[3]), .SE (n_221),
       .SI (\MEM_memo[13] [3]), .Q (\MEM_memo[13] [3]));
  SDFFQX2 \MEM_memo_reg[13][5] (.CK (wclk), .D (wdata[5]), .SE (n_221),
       .SI (\MEM_memo[13] [5]), .Q (\MEM_memo[13] [5]));
  SDFFQX2 \MEM_memo_reg[13][6] (.CK (wclk), .D (wdata[6]), .SE (n_221),
       .SI (\MEM_memo[13] [6]), .Q (\MEM_memo[13] [6]));
  SDFFQX2 \MEM_memo_reg[13][7] (.CK (wclk), .D (wdata[7]), .SE (n_221),
       .SI (\MEM_memo[13] [7]), .Q (\MEM_memo[13] [7]));
  SDFFQX2 \MEM_memo_reg[13][2] (.CK (wclk), .D (wdata[2]), .SE (n_221),
       .SI (\MEM_memo[13] [2]), .Q (\MEM_memo[13] [2]));
  SDFFQX2 \MEM_memo_reg[9][6] (.CK (wclk), .D (wdata[6]), .SE (n_224),
       .SI (\MEM_memo[9] [6]), .Q (\MEM_memo[9] [6]));
  SDFFQX2 \MEM_memo_reg[13][4] (.CK (wclk), .D (wdata[4]), .SE (n_221),
       .SI (\MEM_memo[13] [4]), .Q (\MEM_memo[13] [4]));
  AOI221X2 g5129__2883(.A0 (n_73), .A1 (\MEM_memo[12] [4]), .B0 (n_76),
       .B1 (\MEM_memo[14] [4]), .C0 (n_176), .Y (n_220));
  SDFFRHQX1 \RPTR_rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_247),
       .SE (n_219), .SI (n_218), .Q (rptr[2]));
  AOI221X2 g5120__2346(.A0 (n_215), .A1 (\MEM_memo[3] [7]), .B0
       (n_214), .B1 (\MEM_memo[5] [7]), .C0 (n_153), .Y (n_217));
  AOI221X2 g5121__1666(.A0 (n_215), .A1 (\MEM_memo[3] [2]), .B0
       (n_214), .B1 (\MEM_memo[5] [2]), .C0 (n_173), .Y (n_216));
  AOI221X2 g5122__7410(.A0 (n_211), .A1 (\MEM_memo[9] [7]), .B0
       (n_210), .B1 (\MEM_memo[15] [7]), .C0 (n_161), .Y (n_213));
  AOI221X2 g5123__6417(.A0 (n_211), .A1 (\MEM_memo[9] [2]), .B0
       (n_210), .B1 (\MEM_memo[15] [2]), .C0 (n_162), .Y (n_212));
  AOI221X2 g5124__5477(.A0 (n_211), .A1 (\MEM_memo[1] [5]), .B0
       (n_210), .B1 (\MEM_memo[7] [5]), .C0 (n_169), .Y (n_209));
  AOI221X2 g5125__2398(.A0 (n_192), .A1 (\MEM_memo[8] [6]), .B0
       (n_191), .B1 (\MEM_memo[10] [6]), .C0 (n_166), .Y (n_208));
  AOI221X2 g5126__5107(.A0 (n_215), .A1 (\MEM_memo[11] [1]), .B0
       (n_214), .B1 (\MEM_memo[13] [1]), .C0 (n_177), .Y (n_207));
  MXI2X1 g4972__6260(.A (n_159), .B (n_182), .S0 (wq2_rptr[0]), .Y
       (n_206));
  AOI221X2 g5130__4319(.A0 (n_215), .A1 (\MEM_memo[3] [1]), .B0
       (n_214), .B1 (\MEM_memo[5] [1]), .C0 (n_175), .Y (n_205));
  AOI221X2 g5132__8428(.A0 (n_211), .A1 (\MEM_memo[1] [6]), .B0
       (n_210), .B1 (\MEM_memo[7] [6]), .C0 (n_154), .Y (n_204));
  AOI221X2 g5133__5526(.A0 (n_215), .A1 (\MEM_memo[3] [4]), .B0
       (n_214), .B1 (\MEM_memo[5] [4]), .C0 (n_165), .Y (n_203));
  AOI221X2 g5134__6783(.A0 (n_211), .A1 (\MEM_memo[1] [0]), .B0
       (n_210), .B1 (\MEM_memo[7] [0]), .C0 (n_151), .Y (n_202));
  AOI221X2 g5135__3680(.A0 (n_215), .A1 (\MEM_memo[11] [3]), .B0
       (n_214), .B1 (\MEM_memo[13] [3]), .C0 (n_170), .Y (n_201));
  AOI221X2 g5136__1617(.A0 (n_215), .A1 (\MEM_memo[11] [5]), .B0
       (n_214), .B1 (\MEM_memo[13] [5]), .C0 (n_174), .Y (n_200));
  AOI221X2 g5137__2802(.A0 (n_211), .A1 (\MEM_memo[1] [3]), .B0
       (n_210), .B1 (\MEM_memo[7] [3]), .C0 (n_152), .Y (n_199));
  DFFRHQX2 \R2W_wq1_rptr_reg[1] (.RN (wrst_n), .CK (wclk), .D
       (rptr[1]), .Q (R2W_wq1_rptr[1]));
  INVX3 g4987(.A (n_198), .Y (n_229));
  SDFFQX2 \MEM_memo_reg[11][5] (.CK (wclk), .D (wdata[5]), .SE (n_197),
       .SI (\MEM_memo[11] [5]), .Q (\MEM_memo[11] [5]));
  SDFFQX2 \MEM_memo_reg[11][4] (.CK (wclk), .D (wdata[4]), .SE (n_197),
       .SI (\MEM_memo[11] [4]), .Q (\MEM_memo[11] [4]));
  SDFFQX2 \MEM_memo_reg[7][5] (.CK (wclk), .D (wdata[5]), .SE (n_196),
       .SI (\MEM_memo[7] [5]), .Q (\MEM_memo[7] [5]));
  SDFFQX2 \MEM_memo_reg[11][3] (.CK (wclk), .D (wdata[3]), .SE (n_197),
       .SI (\MEM_memo[11] [3]), .Q (\MEM_memo[11] [3]));
  SDFFHQX4 \MEM_memo_reg[11][0] (.CK (wclk), .D (wdata[0]), .SE
       (n_197), .SI (\MEM_memo[11] [0]), .Q (\MEM_memo[11] [0]));
  SDFFQX2 \MEM_memo_reg[11][1] (.CK (wclk), .D (wdata[1]), .SE (n_197),
       .SI (\MEM_memo[11] [1]), .Q (\MEM_memo[11] [1]));
  SDFFQX2 \MEM_memo_reg[11][2] (.CK (wclk), .D (wdata[2]), .SE (n_197),
       .SI (\MEM_memo[11] [2]), .Q (\MEM_memo[11] [2]));
  SDFFQX2 \MEM_memo_reg[11][6] (.CK (wclk), .D (wdata[6]), .SE (n_197),
       .SI (\MEM_memo[11] [6]), .Q (\MEM_memo[11] [6]));
  SDFFQX2 \MEM_memo_reg[7][4] (.CK (wclk), .D (wdata[4]), .SE (n_196),
       .SI (\MEM_memo[7] [4]), .Q (\MEM_memo[7] [4]));
  DFFRHQX4 \RPTR_rbin_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_225), .Q
       (rptr[4]));
  SDFFQX2 \MEM_memo_reg[11][7] (.CK (wclk), .D (wdata[7]), .SE (n_197),
       .SI (\MEM_memo[11] [7]), .Q (\MEM_memo[11] [7]));
  SDFFQX2 \MEM_memo_reg[7][7] (.CK (wclk), .D (wdata[7]), .SE (n_196),
       .SI (\MEM_memo[7] [7]), .Q (\MEM_memo[7] [7]));
  SDFFQX2 \MEM_memo_reg[7][6] (.CK (wclk), .D (wdata[6]), .SE (n_196),
       .SI (\MEM_memo[7] [6]), .Q (\MEM_memo[7] [6]));
  SDFFQX2 \MEM_memo_reg[7][0] (.CK (wclk), .D (wdata[0]), .SE (n_196),
       .SI (\MEM_memo[7] [0]), .Q (\MEM_memo[7] [0]));
  SDFFQX2 \MEM_memo_reg[7][1] (.CK (wclk), .D (wdata[1]), .SE (n_196),
       .SI (\MEM_memo[7] [1]), .Q (\MEM_memo[7] [1]));
  SDFFQX2 \MEM_memo_reg[7][2] (.CK (wclk), .D (wdata[2]), .SE (n_196),
       .SI (\MEM_memo[7] [2]), .Q (\MEM_memo[7] [2]));
  SDFFQX2 \MEM_memo_reg[7][3] (.CK (wclk), .D (wdata[3]), .SE (n_196),
       .SI (\MEM_memo[7] [3]), .Q (\MEM_memo[7] [3]));
  DFFRHQX4 \WPTR_wbin_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_223), .Q
       (wptr[4]));
  DFFRHQX4 \WPTR_wbin_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_195), .Q
       (waddr[3]));
  INVX1 g5000(.A (n_223), .Y (n_194));
  AOI221X2 g5131__1705(.A0 (n_192), .A1 (\MEM_memo[8] [0]), .B0
       (n_191), .B1 (\MEM_memo[10] [0]), .C0 (n_145), .Y (n_193));
  AOI22X4 g4998__5122(.A0 (n_147), .A1 (n_190), .B0 (n_148), .B1
       (n_189), .Y (n_198));
  SDFFQX2 \MEM_memo_reg[3][7] (.CK (wclk), .D (wdata[7]), .SE (n_187),
       .SI (\MEM_memo[3] [7]), .Q (\MEM_memo[3] [7]));
  SDFFHQX4 \MEM_memo_reg[6][4] (.CK (wclk), .D (wdata[4]), .SE (n_188),
       .SI (\MEM_memo[6] [4]), .Q (\MEM_memo[6] [4]));
  SDFFHQX4 \MEM_memo_reg[2][2] (.CK (wclk), .D (wdata[2]), .SE (n_184),
       .SI (\MEM_memo[2] [2]), .Q (\MEM_memo[2] [2]));
  SDFFQX2 \MEM_memo_reg[5][7] (.CK (wclk), .D (wdata[7]), .SE (n_185),
       .SI (\MEM_memo[5] [7]), .Q (\MEM_memo[5] [7]));
  SDFFQX2 \MEM_memo_reg[6][3] (.CK (wclk), .D (wdata[3]), .SE (n_188),
       .SI (\MEM_memo[6] [3]), .Q (\MEM_memo[6] [3]));
  SDFFQX2 \MEM_memo_reg[1][5] (.CK (wclk), .D (wdata[5]), .SE (n_180),
       .SI (\MEM_memo[1] [5]), .Q (\MEM_memo[1] [5]));
  SDFFQX2 \MEM_memo_reg[15][5] (.CK (wclk), .D (wdata[5]), .SE (n_186),
       .SI (\MEM_memo[15] [5]), .Q (\MEM_memo[15] [5]));
  SDFFQX2 \MEM_memo_reg[3][2] (.CK (wclk), .D (wdata[2]), .SE (n_187),
       .SI (\MEM_memo[3] [2]), .Q (\MEM_memo[3] [2]));
  SDFFQX2 \MEM_memo_reg[15][3] (.CK (wclk), .D (wdata[3]), .SE (n_186),
       .SI (\MEM_memo[15] [3]), .Q (\MEM_memo[15] [3]));
  SDFFQX2 \MEM_memo_reg[15][0] (.CK (wclk), .D (wdata[0]), .SE (n_186),
       .SI (\MEM_memo[15] [0]), .Q (\MEM_memo[15] [0]));
  SDFFQX2 \MEM_memo_reg[15][2] (.CK (wclk), .D (wdata[2]), .SE (n_186),
       .SI (\MEM_memo[15] [2]), .Q (\MEM_memo[15] [2]));
  SDFFQX2 \MEM_memo_reg[15][1] (.CK (wclk), .D (wdata[1]), .SE (n_186),
       .SI (\MEM_memo[15] [1]), .Q (\MEM_memo[15] [1]));
  SDFFQX2 \MEM_memo_reg[15][7] (.CK (wclk), .D (wdata[7]), .SE (n_186),
       .SI (\MEM_memo[15] [7]), .Q (\MEM_memo[15] [7]));
  SDFFQX2 \MEM_memo_reg[15][4] (.CK (wclk), .D (wdata[4]), .SE (n_186),
       .SI (\MEM_memo[15] [4]), .Q (\MEM_memo[15] [4]));
  SDFFQX2 \MEM_memo_reg[15][6] (.CK (wclk), .D (wdata[6]), .SE (n_186),
       .SI (\MEM_memo[15] [6]), .Q (\MEM_memo[15] [6]));
  SDFFQX2 \MEM_memo_reg[5][0] (.CK (wclk), .D (wdata[0]), .SE (n_185),
       .SI (\MEM_memo[5] [0]), .Q (\MEM_memo[5] [0]));
  SDFFHQX4 \MEM_memo_reg[2][3] (.CK (wclk), .D (wdata[3]), .SE (n_184),
       .SI (\MEM_memo[2] [3]), .Q (\MEM_memo[2] [3]));
  SDFFQX2 \MEM_memo_reg[2][4] (.CK (wclk), .D (wdata[4]), .SE (n_184),
       .SI (\MEM_memo[2] [4]), .Q (\MEM_memo[2] [4]));
  SDFFQX2 \MEM_memo_reg[2][5] (.CK (wclk), .D (wdata[5]), .SE (n_184),
       .SI (\MEM_memo[2] [5]), .Q (\MEM_memo[2] [5]));
  SDFFHQX4 \MEM_memo_reg[2][6] (.CK (wclk), .D (wdata[6]), .SE (n_184),
       .SI (\MEM_memo[2] [6]), .Q (\MEM_memo[2] [6]));
  SDFFHQX4 \MEM_memo_reg[2][7] (.CK (wclk), .D (wdata[7]), .SE (n_184),
       .SI (\MEM_memo[2] [7]), .Q (\MEM_memo[2] [7]));
  SDFFQX2 \MEM_memo_reg[3][0] (.CK (wclk), .D (wdata[0]), .SE (n_187),
       .SI (\MEM_memo[3] [0]), .Q (\MEM_memo[3] [0]));
  SDFFQX2 \MEM_memo_reg[3][1] (.CK (wclk), .D (wdata[1]), .SE (n_187),
       .SI (\MEM_memo[3] [1]), .Q (\MEM_memo[3] [1]));
  SDFFQX2 \MEM_memo_reg[3][4] (.CK (wclk), .D (wdata[4]), .SE (n_187),
       .SI (\MEM_memo[3] [4]), .Q (\MEM_memo[3] [4]));
  SDFFQX2 \MEM_memo_reg[3][5] (.CK (wclk), .D (wdata[5]), .SE (n_187),
       .SI (\MEM_memo[3] [5]), .Q (\MEM_memo[3] [5]));
  SDFFQX2 \MEM_memo_reg[3][6] (.CK (wclk), .D (wdata[6]), .SE (n_187),
       .SI (\MEM_memo[3] [6]), .Q (\MEM_memo[3] [6]));
  SDFFHQX4 \MEM_memo_reg[4][0] (.CK (wclk), .D (wdata[0]), .SE (n_183),
       .SI (\MEM_memo[4] [0]), .Q (\MEM_memo[4] [0]));
  SDFFHQX4 \MEM_memo_reg[4][1] (.CK (wclk), .D (wdata[1]), .SE (n_183),
       .SI (\MEM_memo[4] [1]), .Q (\MEM_memo[4] [1]));
  SDFFQX2 \MEM_memo_reg[4][2] (.CK (wclk), .D (wdata[2]), .SE (n_183),
       .SI (\MEM_memo[4] [2]), .Q (\MEM_memo[4] [2]));
  SDFFHQX4 \MEM_memo_reg[4][4] (.CK (wclk), .D (wdata[4]), .SE (n_183),
       .SI (\MEM_memo[4] [4]), .Q (\MEM_memo[4] [4]));
  SDFFQX2 \MEM_memo_reg[4][6] (.CK (wclk), .D (wdata[6]), .SE (n_183),
       .SI (\MEM_memo[4] [6]), .Q (\MEM_memo[4] [6]));
  DFFRHQX1 \WPTR_wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_182), .Q
       (wptr[0]));
  SDFFHQX4 \MEM_memo_reg[4][5] (.CK (wclk), .D (wdata[5]), .SE (n_183),
       .SI (\MEM_memo[4] [5]), .Q (\MEM_memo[4] [5]));
  SDFFQX2 \MEM_memo_reg[5][1] (.CK (wclk), .D (wdata[1]), .SE (n_185),
       .SI (\MEM_memo[5] [1]), .Q (\MEM_memo[5] [1]));
  SDFFQX2 \MEM_memo_reg[5][2] (.CK (wclk), .D (wdata[2]), .SE (n_185),
       .SI (\MEM_memo[5] [2]), .Q (\MEM_memo[5] [2]));
  SDFFQX2 \MEM_memo_reg[5][4] (.CK (wclk), .D (wdata[4]), .SE (n_185),
       .SI (\MEM_memo[5] [4]), .Q (\MEM_memo[5] [4]));
  SDFFQX2 \MEM_memo_reg[5][5] (.CK (wclk), .D (wdata[5]), .SE (n_185),
       .SI (\MEM_memo[5] [5]), .Q (\MEM_memo[5] [5]));
  SDFFQX2 \MEM_memo_reg[5][6] (.CK (wclk), .D (wdata[6]), .SE (n_185),
       .SI (\MEM_memo[5] [6]), .Q (\MEM_memo[5] [6]));
  SDFFHQX4 \MEM_memo_reg[6][0] (.CK (wclk), .D (wdata[0]), .SE (n_188),
       .SI (\MEM_memo[6] [0]), .Q (\MEM_memo[6] [0]));
  SDFFHQX4 \MEM_memo_reg[6][1] (.CK (wclk), .D (wdata[1]), .SE (n_188),
       .SI (\MEM_memo[6] [1]), .Q (\MEM_memo[6] [1]));
  SDFFQX2 \MEM_memo_reg[6][2] (.CK (wclk), .D (wdata[2]), .SE (n_188),
       .SI (\MEM_memo[6] [2]), .Q (\MEM_memo[6] [2]));
  SDFFQX2 \MEM_memo_reg[6][6] (.CK (wclk), .D (wdata[6]), .SE (n_188),
       .SI (\MEM_memo[6] [6]), .Q (\MEM_memo[6] [6]));
  SDFFQX2 \MEM_memo_reg[6][7] (.CK (wclk), .D (wdata[7]), .SE (n_188),
       .SI (\MEM_memo[6] [7]), .Q (\MEM_memo[6] [7]));
  SDFFHQX4 \MEM_memo_reg[6][5] (.CK (wclk), .D (wdata[5]), .SE (n_188),
       .SI (\MEM_memo[6] [5]), .Q (\MEM_memo[6] [5]));
  SDFFHQX4 \MEM_memo_reg[0][2] (.CK (wclk), .D (wdata[2]), .SE (n_181),
       .SI (\MEM_memo[0] [2]), .Q (\MEM_memo[0] [2]));
  SDFFQX2 \MEM_memo_reg[0][0] (.CK (wclk), .D (wdata[0]), .SE (n_181),
       .SI (\MEM_memo[0] [0]), .Q (\MEM_memo[0] [0]));
  SDFFQX2 \MEM_memo_reg[0][1] (.CK (wclk), .D (wdata[1]), .SE (n_181),
       .SI (\MEM_memo[0] [1]), .Q (\MEM_memo[0] [1]));
  SDFFHQX4 \MEM_memo_reg[0][3] (.CK (wclk), .D (wdata[3]), .SE (n_181),
       .SI (\MEM_memo[0] [3]), .Q (\MEM_memo[0] [3]));
  SDFFQX2 \MEM_memo_reg[0][4] (.CK (wclk), .D (wdata[4]), .SE (n_181),
       .SI (\MEM_memo[0] [4]), .Q (\MEM_memo[0] [4]));
  SDFFQX2 \MEM_memo_reg[0][5] (.CK (wclk), .D (wdata[5]), .SE (n_181),
       .SI (\MEM_memo[0] [5]), .Q (\MEM_memo[0] [5]));
  SDFFHQX4 \MEM_memo_reg[0][6] (.CK (wclk), .D (wdata[6]), .SE (n_181),
       .SI (\MEM_memo[0] [6]), .Q (\MEM_memo[0] [6]));
  SDFFHQX4 \MEM_memo_reg[0][7] (.CK (wclk), .D (wdata[7]), .SE (n_181),
       .SI (\MEM_memo[0] [7]), .Q (\MEM_memo[0] [7]));
  SDFFQX2 \MEM_memo_reg[1][0] (.CK (wclk), .D (wdata[0]), .SE (n_180),
       .SI (\MEM_memo[1] [0]), .Q (\MEM_memo[1] [0]));
  SDFFQX2 \MEM_memo_reg[1][1] (.CK (wclk), .D (wdata[1]), .SE (n_180),
       .SI (\MEM_memo[1] [1]), .Q (\MEM_memo[1] [1]));
  SDFFQX2 \MEM_memo_reg[1][2] (.CK (wclk), .D (wdata[2]), .SE (n_180),
       .SI (\MEM_memo[1] [2]), .Q (\MEM_memo[1] [2]));
  SDFFQX2 \MEM_memo_reg[1][3] (.CK (wclk), .D (wdata[3]), .SE (n_180),
       .SI (\MEM_memo[1] [3]), .Q (\MEM_memo[1] [3]));
  SDFFQX2 \MEM_memo_reg[1][4] (.CK (wclk), .D (wdata[4]), .SE (n_180),
       .SI (\MEM_memo[1] [4]), .Q (\MEM_memo[1] [4]));
  SDFFQX2 \MEM_memo_reg[1][6] (.CK (wclk), .D (wdata[6]), .SE (n_180),
       .SI (\MEM_memo[1] [6]), .Q (\MEM_memo[1] [6]));
  SDFFQX2 \MEM_memo_reg[1][7] (.CK (wclk), .D (wdata[7]), .SE (n_180),
       .SI (\MEM_memo[1] [7]), .Q (\MEM_memo[1] [7]));
  SDFFQX2 \MEM_memo_reg[2][0] (.CK (wclk), .D (wdata[0]), .SE (n_184),
       .SI (\MEM_memo[2] [0]), .Q (\MEM_memo[2] [0]));
  SDFFQX2 \MEM_memo_reg[2][1] (.CK (wclk), .D (wdata[1]), .SE (n_184),
       .SI (\MEM_memo[2] [1]), .Q (\MEM_memo[2] [1]));
  SDFFQX2 \MEM_memo_reg[3][3] (.CK (wclk), .D (wdata[3]), .SE (n_187),
       .SI (\MEM_memo[3] [3]), .Q (\MEM_memo[3] [3]));
  SDFFQX2 \MEM_memo_reg[5][3] (.CK (wclk), .D (wdata[3]), .SE (n_185),
       .SI (\MEM_memo[5] [3]), .Q (\MEM_memo[5] [3]));
  SDFFQX2 \MEM_memo_reg[4][7] (.CK (wclk), .D (wdata[7]), .SE (n_183),
       .SI (\MEM_memo[4] [7]), .Q (\MEM_memo[4] [7]));
  SDFFQX2 \MEM_memo_reg[4][3] (.CK (wclk), .D (wdata[3]), .SE (n_183),
       .SI (\MEM_memo[4] [3]), .Q (\MEM_memo[4] [3]));
  SDFFRHQX8 \RPTR_rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_179),
       .SE (n_178), .SI (n_219), .Q (rptr[1]));
  OAI2BB2X4 g5004__8246(.A0N (n_186), .A1N (wptr[4]), .B0 (n_186), .B1
       (wptr[4]), .Y (n_223));
  DFFRHQX1 \R2W_wq1_rptr_reg[0] (.RN (wrst_n), .CK (wclk), .D
       (rptr[0]), .Q (R2W_wq1_rptr[0]));
  INVX1 g4976(.A (n_222), .Y (n_195));
  INVX2 g4931(.A (n_227), .Y (n_225));
  OAI221X2 g5140__7098(.A0 (n_172), .A1 (n_48), .B0 (n_171), .B1
       (n_38), .C0 (n_143), .Y (n_177));
  OAI221X2 g5149__6131(.A0 (n_168), .A1 (n_18), .B0 (n_167), .B1 (n_2),
       .C0 (n_130), .Y (n_176));
  OAI221X2 g5150__1881(.A0 (n_164), .A1 (n_8), .B0 (n_163), .B1 (n_56),
       .C0 (n_131), .Y (n_175));
  OAI221X2 g5147__5115(.A0 (n_84), .A1 (n_36), .B0 (n_72), .B1 (n_22),
       .C0 (n_129), .Y (n_174));
  OAI221X2 g5146__7482(.A0 (n_172), .A1 (n_24), .B0 (n_171), .B1 (n_7),
       .C0 (n_141), .Y (n_173));
  OAI221X2 g5154__4733(.A0 (n_172), .A1 (n_34), .B0 (n_171), .B1
       (n_41), .C0 (n_140), .Y (n_170));
  OAI221X2 g5145__6161(.A0 (n_168), .A1 (n_13), .B0 (n_167), .B1
       (n_21), .C0 (n_142), .Y (n_169));
  OAI221X2 g5144__9315(.A0 (n_168), .A1 (n_46), .B0 (n_167), .B1
       (n_37), .C0 (n_125), .Y (n_166));
  OAI221X2 g5152__9945(.A0 (n_164), .A1 (n_43), .B0 (n_163), .B1
       (n_64), .C0 (n_126), .Y (n_165));
  OAI221X2 g5143__2883(.A0 (n_164), .A1 (n_53), .B0 (n_163), .B1
       (n_47), .C0 (n_139), .Y (n_162));
  OAI221X2 g5142__2346(.A0 (n_164), .A1 (n_9), .B0 (n_163), .B1 (n_50),
       .C0 (n_128), .Y (n_161));
  SDFFQX2 \MEM_memo_reg[14][1] (.CK (wclk), .D (wdata[1]), .SE (n_160),
       .SI (\MEM_memo[14] [1]), .Q (\MEM_memo[14] [1]));
  DFFRHQX4 \RPTR_rbin_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_247), .Q
       (raddr[3]));
  SDFFHQX4 \MEM_memo_reg[14][5] (.CK (wclk), .D (wdata[5]), .SE
       (n_160), .SI (\MEM_memo[14] [5]), .Q (\MEM_memo[14] [5]));
  SDFFHQX4 \MEM_memo_reg[14][7] (.CK (wclk), .D (wdata[7]), .SE
       (n_160), .SI (\MEM_memo[14] [7]), .Q (\MEM_memo[14] [7]));
  SDFFHQX4 \MEM_memo_reg[10][4] (.CK (wclk), .D (wdata[4]), .SE
       (n_149), .SI (\MEM_memo[10] [4]), .Q (\MEM_memo[10] [4]));
  INVX2 g4999(.A (n_159), .Y (n_182));
  SDFFQX2 \MEM_memo_reg[8][0] (.CK (wclk), .D (wdata[0]), .SE (n_150),
       .SI (\MEM_memo[8] [0]), .Q (\MEM_memo[8] [0]));
  SDFFHQX4 \MEM_memo_reg[12][5] (.CK (wclk), .D (wdata[5]), .SE
       (n_158), .SI (\MEM_memo[12] [5]), .Q (\MEM_memo[12] [5]));
  SDFFQX2 \MEM_memo_reg[14][4] (.CK (wclk), .D (wdata[4]), .SE (n_160),
       .SI (\MEM_memo[14] [4]), .Q (\MEM_memo[14] [4]));
  SDFFQX2 \MEM_memo_reg[12][4] (.CK (wclk), .D (wdata[4]), .SE (n_158),
       .SI (\MEM_memo[12] [4]), .Q (\MEM_memo[12] [4]));
  SDFFQX2 \MEM_memo_reg[12][0] (.CK (wclk), .D (wdata[0]), .SE (n_158),
       .SI (\MEM_memo[12] [0]), .Q (\MEM_memo[12] [0]));
  AOI21X4 g4986__1666(.A0 (n_114), .A1 (waddr[3]), .B0 (n_144), .Y
       (n_222));
  AOI2BB2X4 g4934__7410(.A0N (n_157), .A1N (n_156), .B0 (n_157), .B1
       (n_156), .Y (n_227));
  NAND2X6 g5006__6417(.A (n_155), .B (waddr[2]), .Y (n_221));
  NAND2BX4 g5005__5477(.AN (waddr[2]), .B (n_155), .Y (n_224));
  DFFRHQX8 \WPTR_wbin_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_189), .Q
       (waddr[2]));
  OAI221X2 g5157__2398(.A0 (n_172), .A1 (n_27), .B0 (n_171), .B1
       (n_35), .C0 (n_138), .Y (n_154));
  OAI221X2 g5156__5107(.A0 (n_172), .A1 (n_28), .B0 (n_171), .B1
       (n_49), .C0 (n_132), .Y (n_153));
  OAI221X2 g5155__6260(.A0 (n_172), .A1 (n_16), .B0 (n_171), .B1
       (n_51), .C0 (n_124), .Y (n_152));
  OAI221X2 g5153__4319(.A0 (n_164), .A1 (n_29), .B0 (n_163), .B1
       (n_45), .C0 (n_127), .Y (n_151));
  SDFFQX2 \MEM_memo_reg[8][7] (.CK (wclk), .D (wdata[7]), .SE (n_150),
       .SI (\MEM_memo[8] [7]), .Q (\MEM_memo[8] [7]));
  SDFFQX2 \MEM_memo_reg[10][0] (.CK (wclk), .D (wdata[0]), .SE (n_149),
       .SI (\MEM_memo[10] [0]), .Q (\MEM_memo[10] [0]));
  SDFFHQX4 \MEM_memo_reg[10][1] (.CK (wclk), .D (wdata[1]), .SE
       (n_149), .SI (\MEM_memo[10] [1]), .Q (\MEM_memo[10] [1]));
  SDFFQX2 \MEM_memo_reg[10][2] (.CK (wclk), .D (wdata[2]), .SE (n_149),
       .SI (\MEM_memo[10] [2]), .Q (\MEM_memo[10] [2]));
  SDFFHQX4 \MEM_memo_reg[10][3] (.CK (wclk), .D (wdata[3]), .SE
       (n_149), .SI (\MEM_memo[10] [3]), .Q (\MEM_memo[10] [3]));
  SDFFQX2 \MEM_memo_reg[10][5] (.CK (wclk), .D (wdata[5]), .SE (n_149),
       .SI (\MEM_memo[10] [5]), .Q (\MEM_memo[10] [5]));
  SDFFQX2 \MEM_memo_reg[10][7] (.CK (wclk), .D (wdata[7]), .SE (n_149),
       .SI (\MEM_memo[10] [7]), .Q (\MEM_memo[10] [7]));
  SDFFQX2 \MEM_memo_reg[10][6] (.CK (wclk), .D (wdata[6]), .SE (n_149),
       .SI (\MEM_memo[10] [6]), .Q (\MEM_memo[10] [6]));
  SDFFQX2 \MEM_memo_reg[12][1] (.CK (wclk), .D (wdata[1]), .SE (n_158),
       .SI (\MEM_memo[12] [1]), .Q (\MEM_memo[12] [1]));
  SDFFHQX4 \MEM_memo_reg[12][2] (.CK (wclk), .D (wdata[2]), .SE
       (n_158), .SI (\MEM_memo[12] [2]), .Q (\MEM_memo[12] [2]));
  SDFFQX2 \MEM_memo_reg[12][3] (.CK (wclk), .D (wdata[3]), .SE (n_158),
       .SI (\MEM_memo[12] [3]), .Q (\MEM_memo[12] [3]));
  SDFFQX2 \MEM_memo_reg[8][2] (.CK (wclk), .D (wdata[2]), .SE (n_150),
       .SI (\MEM_memo[8] [2]), .Q (\MEM_memo[8] [2]));
  SDFFHQX4 \MEM_memo_reg[12][7] (.CK (wclk), .D (wdata[7]), .SE
       (n_158), .SI (\MEM_memo[12] [7]), .Q (\MEM_memo[12] [7]));
  SDFFHQX4 \MEM_memo_reg[12][6] (.CK (wclk), .D (wdata[6]), .SE
       (n_158), .SI (\MEM_memo[12] [6]), .Q (\MEM_memo[12] [6]));
  SDFFHQX4 \MEM_memo_reg[8][1] (.CK (wclk), .D (wdata[1]), .SE (n_150),
       .SI (\MEM_memo[8] [1]), .Q (\MEM_memo[8] [1]));
  SDFFQX2 \MEM_memo_reg[14][0] (.CK (wclk), .D (wdata[0]), .SE (n_160),
       .SI (\MEM_memo[14] [0]), .Q (\MEM_memo[14] [0]));
  SDFFQX2 \MEM_memo_reg[14][3] (.CK (wclk), .D (wdata[3]), .SE (n_160),
       .SI (\MEM_memo[14] [3]), .Q (\MEM_memo[14] [3]));
  SDFFHQX4 \MEM_memo_reg[14][2] (.CK (wclk), .D (wdata[2]), .SE
       (n_160), .SI (\MEM_memo[14] [2]), .Q (\MEM_memo[14] [2]));
  SDFFHQX4 \MEM_memo_reg[14][6] (.CK (wclk), .D (wdata[6]), .SE
       (n_160), .SI (\MEM_memo[14] [6]), .Q (\MEM_memo[14] [6]));
  SDFFHQX4 \MEM_memo_reg[8][3] (.CK (wclk), .D (wdata[3]), .SE (n_150),
       .SI (\MEM_memo[8] [3]), .Q (\MEM_memo[8] [3]));
  SDFFQX2 \MEM_memo_reg[8][5] (.CK (wclk), .D (wdata[5]), .SE (n_150),
       .SI (\MEM_memo[8] [5]), .Q (\MEM_memo[8] [5]));
  SDFFHQX4 \MEM_memo_reg[8][4] (.CK (wclk), .D (wdata[4]), .SE (n_150),
       .SI (\MEM_memo[8] [4]), .Q (\MEM_memo[8] [4]));
  SDFFQX2 \MEM_memo_reg[8][6] (.CK (wclk), .D (wdata[6]), .SE (n_150),
       .SI (\MEM_memo[8] [6]), .Q (\MEM_memo[8] [6]));
  AOI22X2 g5003__8428(.A0 (n_92), .A1 (n_148), .B0 (n_91), .B1 (n_147),
       .Y (n_159));
  INVX4 g5015(.A (n_189), .Y (n_190));
  NAND2BX4 g5127__5526(.AN (waddr[2]), .B (n_121), .Y (n_197));
  SDFFRHQX1 \RPTR_rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_146),
       .SE (n_88), .SI (n_178), .Q (rptr[0]));
  OAI221X2 g5151__6783(.A0 (n_172), .A1 (n_39), .B0 (n_171), .B1
       (n_57), .C0 (n_122), .Y (n_145));
  INVX1 g4940(.A (n_247), .Y (n_218));
  INVX3 g5160(.A (n_144), .Y (n_196));
  AOI221X2 g5182__3680(.A0 (n_211), .A1 (\MEM_memo[9] [1]), .B0
       (n_210), .B1 (\MEM_memo[15] [1]), .C0 (n_101), .Y (n_143));
  AOI221X4 g5181__1617(.A0 (n_191), .A1 (\MEM_memo[2] [5]), .B0
       (n_192), .B1 (\MEM_memo[0] [5]), .C0 (n_97), .Y (n_142));
  AOI221X2 g5180__2802(.A0 (n_211), .A1 (\MEM_memo[1] [2]), .B0
       (n_210), .B1 (\MEM_memo[7] [2]), .C0 (n_103), .Y (n_141));
  AOI221X2 g5179__1705(.A0 (n_211), .A1 (\MEM_memo[9] [3]), .B0
       (n_210), .B1 (\MEM_memo[15] [3]), .C0 (n_107), .Y (n_140));
  AOI221X4 g5178__5122(.A0 (n_215), .A1 (\MEM_memo[11] [2]), .B0
       (n_214), .B1 (\MEM_memo[13] [2]), .C0 (n_104), .Y (n_139));
  AOI221X4 g5177__8246(.A0 (n_215), .A1 (\MEM_memo[3] [6]), .B0
       (n_214), .B1 (\MEM_memo[5] [6]), .C0 (n_96), .Y (n_138));
  NOR2BX4 g5176__7098(.AN (waddr[2]), .B (n_134), .Y (n_144));
  OR2X6 g5175__6131(.A (n_133), .B (waddr[2]), .Y (n_181));
  OR2X6 g5174__1881(.A (n_137), .B (waddr[2]), .Y (n_180));
  OR2X6 g5172__5115(.A (n_137), .B (n_136), .Y (n_185));
  OR2X6 g5171__7482(.A (n_135), .B (n_136), .Y (n_188));
  OR2X6 g5169__4733(.A (n_135), .B (waddr[2]), .Y (n_184));
  OR2X6 g5165__6161(.A (n_134), .B (waddr[2]), .Y (n_187));
  OR2X6 g5168__9315(.A (n_133), .B (n_136), .Y (n_183));
  AOI221X2 g5191__9945(.A0 (n_211), .A1 (\MEM_memo[1] [7]), .B0
       (n_210), .B1 (\MEM_memo[7] [7]), .C0 (n_93), .Y (n_132));
  AOI221X2 g5184__2883(.A0 (n_211), .A1 (\MEM_memo[1] [1]), .B0
       (n_210), .B1 (\MEM_memo[7] [1]), .C0 (n_98), .Y (n_131));
  AOI221X2 g5185__2346(.A0 (n_211), .A1 (\MEM_memo[9] [4]), .B0
       (n_210), .B1 (\MEM_memo[15] [4]), .C0 (n_102), .Y (n_130));
  AOI221X4 g5187__1666(.A0 (n_191), .A1 (\MEM_memo[10] [5]), .B0
       (n_192), .B1 (\MEM_memo[8] [5]), .C0 (n_106), .Y (n_129));
  AOI221X4 g5188__7410(.A0 (n_214), .A1 (\MEM_memo[13] [7]), .B0
       (n_215), .B1 (\MEM_memo[11] [7]), .C0 (n_99), .Y (n_128));
  AOI221X4 g5189__6417(.A0 (n_214), .A1 (\MEM_memo[5] [0]), .B0
       (n_215), .B1 (\MEM_memo[3] [0]), .C0 (n_95), .Y (n_127));
  AOI221X2 g5190__5477(.A0 (n_211), .A1 (\MEM_memo[1] [4]), .B0
       (n_210), .B1 (\MEM_memo[7] [4]), .C0 (n_94), .Y (n_126));
  AOI221X2 g5183__2398(.A0 (n_211), .A1 (\MEM_memo[9] [6]), .B0
       (n_210), .B1 (\MEM_memo[15] [6]), .C0 (n_108), .Y (n_125));
  AOI221X4 g5192__5107(.A0 (n_214), .A1 (\MEM_memo[5] [3]), .B0
       (n_215), .B1 (\MEM_memo[3] [3]), .C0 (n_105), .Y (n_124));
  NOR2X8 g5017__6260(.A (n_113), .B (n_112), .Y (n_155));
  DFFRHQX4 \WPTR_wbin_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_147), .Q
       (waddr[1]));
  OAI2BB2X4 g5138__4319(.A0N (n_123), .A1N (waddr[2]), .B0 (n_123), .B1
       (waddr[2]), .Y (n_189));
  XOR2X2 g4966__8428(.A (n_237), .B (n_119), .Y (n_247));
  DFFRHQX8 \RPTR_rbin_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_219), .Q
       (raddr[2]));
  OR2X6 g5128__5526(.A (n_120), .B (n_136), .Y (n_186));
  AOI221X2 g5186__6783(.A0 (n_211), .A1 (\MEM_memo[9] [0]), .B0
       (n_210), .B1 (\MEM_memo[15] [0]), .C0 (n_87), .Y (n_122));
  INVX2 g4975(.A (n_219), .Y (n_179));
  INVX2 g5139(.A (n_120), .Y (n_121));
  NOR2X4 g4973__3680(.A (n_237), .B (n_119), .Y (n_156));
  NAND2BX4 g5204__1617(.AN (n_118), .B (n_110), .Y (n_134));
  NAND2BX4 g5202__2802(.AN (waddr[0]), .B (n_117), .Y (n_133));
  NAND2BX4 g5201__1705(.AN (n_118), .B (n_117), .Y (n_137));
  NAND2X6 g5166__5122(.A (n_116), .B (n_136), .Y (n_150));
  NAND2X6 g5170__8246(.A (n_116), .B (waddr[2]), .Y (n_158));
  NAND2X6 g5173__7098(.A (n_115), .B (waddr[2]), .Y (n_160));
  NAND2X6 g5167__6131(.A (n_115), .B (n_136), .Y (n_149));
  NAND2BX4 g5141__1881(.AN (n_136), .B (n_111), .Y (n_114));
  INVX6 g5118(.A (n_109), .Y (n_113));
  NAND2BX4 g5148__5115(.AN (n_112), .B (n_111), .Y (n_120));
  NAND2BX4 g5205__7482(.AN (waddr[0]), .B (n_110), .Y (n_135));
  INVX8 g5117(.A (n_148), .Y (n_147));
  XNOR2X2 g5014__4733(.A (n_74), .B (n_100), .Y (n_219));
  DFFRHQX4 \RPTR_rbin_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_146), .Q
       (raddr[1]));
  ADDHX4 g5119__6161(.A (n_80), .B (n_89), .CO (n_109), .S (n_148));
  OAI22X4 g5209__9315(.A0 (n_172), .A1 (n_40), .B0 (n_171), .B1 (n_60),
       .Y (n_108));
  OAI22X4 g5196__9945(.A0 (n_164), .A1 (n_52), .B0 (n_163), .B1 (n_54),
       .Y (n_107));
  OAI22X4 g5197__2883(.A0 (n_172), .A1 (n_3), .B0 (n_171), .B1 (n_26),
       .Y (n_106));
  OAI22X4 g5198__2346(.A0 (n_164), .A1 (n_42), .B0 (n_163), .B1 (n_62),
       .Y (n_105));
  OAI22X4 g5199__1666(.A0 (n_172), .A1 (n_44), .B0 (n_171), .B1 (n_58),
       .Y (n_104));
  OAI22X4 g5200__7410(.A0 (n_164), .A1 (n_55), .B0 (n_163), .B1 (n_19),
       .Y (n_103));
  OAI22X4 g5207__6417(.A0 (n_164), .A1 (n_25), .B0 (n_163), .B1 (n_14),
       .Y (n_102));
  OAI22X4 g5208__5477(.A0 (n_164), .A1 (n_31), .B0 (n_163), .B1 (n_59),
       .Y (n_101));
  NAND2X4 g5063__2398(.A (raddr[2]), .B (n_100), .Y (n_119));
  OAI22X4 g5210__5107(.A0 (n_172), .A1 (n_30), .B0 (n_171), .B1 (n_0),
       .Y (n_99));
  OAI22X4 g5211__6260(.A0 (n_172), .A1 (n_12), .B0 (n_171), .B1 (n_63),
       .Y (n_98));
  OAI22X4 g5212__4319(.A0 (n_172), .A1 (n_32), .B0 (n_171), .B1 (n_33),
       .Y (n_97));
  OAI22X4 g5217__8428(.A0 (n_164), .A1 (n_65), .B0 (n_163), .B1 (n_20),
       .Y (n_96));
  OAI22X4 g5214__5526(.A0 (n_172), .A1 (n_11), .B0 (n_171), .B1 (n_10),
       .Y (n_95));
  OAI22X4 g5215__6783(.A0 (n_172), .A1 (n_23), .B0 (n_171), .B1 (n_61),
       .Y (n_94));
  OAI22X4 g5216__3680(.A0 (n_164), .A1 (n_4), .B0 (n_163), .B1 (n_15),
       .Y (n_93));
  INVX2 g5159(.A (n_111), .Y (n_123));
  INVX2 g5116(.A (n_146), .Y (n_178));
  DFFRHQX4 \WPTR_wbin_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_92), .Q
       (waddr[0]));
  INVX2 g5194(.A (n_92), .Y (n_91));
  NOR2X8 g5203__1617(.A (n_90), .B (waddr[1]), .Y (n_116));
  NOR2X8 g5206__2802(.A (n_90), .B (n_89), .Y (n_115));
  DFFRHQX4 \RPTR_rbin_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_88), .Q
       (raddr[0]));
  OAI22X4 g5213__1705(.A0 (n_168), .A1 (n_5), .B0 (n_167), .B1 (n_6),
       .Y (n_87));
  NOR2X8 g5218__5122(.A (n_86), .B (n_89), .Y (n_110));
  NOR2X6 g5219__8246(.A (n_86), .B (waddr[1]), .Y (n_117));
  NOR2X8 g5162__7098(.A (n_81), .B (n_89), .Y (n_111));
  XOR2X2 g5158__6131(.A (n_83), .B (n_82), .Y (n_146));
  INVX2 g5193(.A (n_88), .Y (n_85));
  OAI22X4 g5221__1881(.A0 (n_75), .A1 (waddr[0]), .B0 (n_79), .B1
       (n_118), .Y (n_92));
  INVX1 g5223(.A (n_211), .Y (n_84));
  NOR2X4 g5161__5115(.A (n_83), .B (n_82), .Y (n_100));
  INVX4 g5195(.A (n_80), .Y (n_81));
  NAND3X8 g5220__7482(.A (n_79), .B (waddr[3]), .C (n_118), .Y (n_90));
  OAI2BB2X4 g5222__4733(.A0N (n_78), .A1N (n_77), .B0 (n_78), .B1
       (n_77), .Y (n_88));
  INVX16 g5226(.A (n_76), .Y (n_171));
  NAND2X8 g5237__6161(.A (n_79), .B (n_112), .Y (n_86));
  INVX8 g5236(.A (n_164), .Y (n_192));
  INVX12 g5225(.A (n_168), .Y (n_214));
  INVX16 g5233(.A (n_191), .Y (n_163));
  NOR2X8 g5229__9315(.A (raddr[2]), .B (n_70), .Y (n_211));
  NOR2X6 g5228__9945(.A (n_75), .B (n_118), .Y (n_80));
  NOR2X6 g5232__2883(.A (n_74), .B (n_71), .Y (n_76));
  NAND2X6 g5231__2346(.A (raddr[2]), .B (n_69), .Y (n_168));
  INVX16 g5224(.A (n_73), .Y (n_172));
  INVX1 g5235(.A (n_210), .Y (n_72));
  NAND2X4 g5239__1666(.A (raddr[0]), .B (n_77), .Y (n_82));
  NOR2X6 g5240__7410(.A (raddr[2]), .B (n_71), .Y (n_191));
  INVX12 g5234(.A (n_167), .Y (n_215));
  NAND2X8 g5243__6417(.A (n_74), .B (n_67), .Y (n_164));
  DFFRXL \R2W_wq2_rptr_reg[4] (.RN (wrst_n), .CK (wclk), .D
       (R2W_wq1_rptr[4]), .Q (UNCONNECTED3), .QN (wq2_rptr[4]));
  DFFRHQX4 \W2R_rq2_wptr_reg[4] (.RN (rrst_n), .CK (rclk), .D
       (W2R_rq1_wptr[4]), .Q (rq2_wptr[4]));
  NOR2X6 g5230__5477(.A (n_74), .B (n_66), .Y (n_73));
  INVX3 g5245(.A (n_69), .Y (n_70));
  INVX3 g5250(.A (n_75), .Y (n_79));
  OR2X8 g5241__2398(.A (raddr[2]), .B (n_68), .Y (n_167));
  NOR2X8 g5242__5107(.A (n_74), .B (n_68), .Y (n_210));
  INVX8 g5244(.A (n_66), .Y (n_67));
  NOR2X4 g5248__6260(.A (raddr[1]), .B (n_78), .Y (n_69));
  NAND2X4 g5254__4319(.A (raddr[1]), .B (n_78), .Y (n_71));
  NOR2X6 g5249__8428(.A (n_17), .B (rempty), .Y (n_77));
  NAND2X8 g5255__5526(.A (winc), .B (n_1), .Y (n_75));
  DFFRHQX2 \R2W_wq1_rptr_reg[4] (.RN (wrst_n), .CK (wclk), .D
       (rptr[4]), .Q (R2W_wq1_rptr[4]));
  NAND2X2 g5253__6783(.A (raddr[0]), .B (raddr[1]), .Y (n_68));
  DFFRXL \R2W_wq2_rptr_reg[0] (.RN (wrst_n), .CK (wclk), .D
       (R2W_wq1_rptr[0]), .Q (UNCONNECTED4), .QN (wq2_rptr[0]));
  DFFRHQX2 \W2R_rq1_wptr_reg[4] (.RN (rrst_n), .CK (rclk), .D
       (wptr[4]), .Q (W2R_rq1_wptr[4]));
  OR2X6 g5247__3680(.A (raddr[1]), .B (raddr[0]), .Y (n_66));
  INVX3 g5275(.A (\MEM_memo[0] [6]), .Y (n_65));
  INVX2 g5321(.A (\MEM_memo[2] [4]), .Y (n_64));
  INVX3 g5320(.A (\MEM_memo[6] [1]), .Y (n_63));
  INVX3 g5310(.A (\MEM_memo[2] [3]), .Y (n_62));
  INVX3 g5318(.A (\MEM_memo[6] [4]), .Y (n_61));
  INVX3 g5308(.A (\MEM_memo[14] [6]), .Y (n_60));
  INVX3 g5300(.A (\MEM_memo[10] [1]), .Y (n_59));
  INVX3 g5281(.A (\MEM_memo[14] [2]), .Y (n_58));
  INVX2 g5313(.A (\MEM_memo[14] [0]), .Y (n_57));
  INVX2 g5326(.A (\MEM_memo[2] [1]), .Y (n_56));
  INVX3 g5315(.A (\MEM_memo[0] [2]), .Y (n_55));
  INVX3 g5264(.A (\MEM_memo[10] [3]), .Y (n_54));
  INVX2 g5276(.A (\MEM_memo[8] [2]), .Y (n_53));
  INVX3 g5272(.A (\MEM_memo[8] [3]), .Y (n_52));
  INVX2 g5270(.A (\MEM_memo[6] [3]), .Y (n_51));
  INVX2 g5285(.A (\MEM_memo[10] [7]), .Y (n_50));
  INVX2 g5317(.A (\MEM_memo[6] [7]), .Y (n_49));
  INVX2 g5278(.A (\MEM_memo[12] [1]), .Y (n_48));
  INVX2 g5262(.A (\MEM_memo[10] [2]), .Y (n_47));
  INVX2 g5306(.A (\MEM_memo[13] [6]), .Y (n_46));
  INVX2 g5268(.A (\MEM_memo[2] [0]), .Y (n_45));
  INVX3 g5322(.A (\MEM_memo[12] [2]), .Y (n_44));
  INVX2 g5299(.A (\MEM_memo[0] [4]), .Y (n_43));
  INVX3 g5295(.A (\MEM_memo[0] [3]), .Y (n_42));
  INVX2 g5288(.A (\MEM_memo[14] [3]), .Y (n_41));
  INVX3 g5258(.A (\MEM_memo[12] [6]), .Y (n_40));
  INVX2 g5282(.A (\MEM_memo[12] [0]), .Y (n_39));
  INVX2 g5298(.A (\MEM_memo[14] [1]), .Y (n_38));
  INVX2 g5283(.A (\MEM_memo[11] [6]), .Y (n_37));
  INVX2 g5304(.A (\MEM_memo[9] [5]), .Y (n_36));
  INVX2 g5309(.A (\MEM_memo[6] [6]), .Y (n_35));
  INVX2 g5273(.A (\MEM_memo[12] [3]), .Y (n_34));
  INVX2 g5290(.A (raddr[1]), .Y (n_83));
  INVX12 g5291(.A (waddr[1]), .Y (n_89));
  INVX12 g5292(.A (raddr[2]), .Y (n_74));
  INVX8 g5293(.A (waddr[2]), .Y (n_136));
  INVX8 g5294(.A (raddr[3]), .Y (n_237));
  INVX3 g5296(.A (\MEM_memo[6] [5]), .Y (n_33));
  INVX3 g5323(.A (\MEM_memo[4] [5]), .Y (n_32));
  INVX3 g5269(.A (\MEM_memo[8] [1]), .Y (n_31));
  INVX3 g5319(.A (\MEM_memo[12] [7]), .Y (n_30));
  INVX2 g5260(.A (\MEM_memo[0] [0]), .Y (n_29));
  INVX2 g5271(.A (\MEM_memo[4] [7]), .Y (n_28));
  INVX2 g5261(.A (\MEM_memo[4] [6]), .Y (n_27));
  INVX3 g5316(.A (\MEM_memo[14] [5]), .Y (n_26));
  INVX3 g5274(.A (\MEM_memo[8] [4]), .Y (n_25));
  INVX2 g5301(.A (\MEM_memo[4] [2]), .Y (n_24));
  INVX3 g5280(.A (\MEM_memo[4] [4]), .Y (n_23));
  INVX2 g5314(.A (\MEM_memo[15] [5]), .Y (n_22));
  INVX2 g5266(.A (\MEM_memo[3] [5]), .Y (n_21));
  INVX3 g5302(.A (\MEM_memo[2] [6]), .Y (n_20));
  INVX3 g5303(.A (\MEM_memo[2] [2]), .Y (n_19));
  INVX2 g5324(.A (\MEM_memo[13] [4]), .Y (n_18));
  INVXL g5256(.A (rinc), .Y (n_17));
  INVX2 g5311(.A (\MEM_memo[4] [3]), .Y (n_16));
  INVX3 g5286(.A (\MEM_memo[2] [7]), .Y (n_15));
  INVX3 g5287(.A (\MEM_memo[10] [4]), .Y (n_14));
  INVX2 g5277(.A (\MEM_memo[5] [5]), .Y (n_13));
  INVX3 g5267(.A (\MEM_memo[4] [1]), .Y (n_12));
  INVX3 g5259(.A (\MEM_memo[4] [0]), .Y (n_11));
  INVX3 g5307(.A (\MEM_memo[6] [0]), .Y (n_10));
  INVX2 g5257(.A (\MEM_memo[8] [7]), .Y (n_9));
  INVX2 g5327(.A (\MEM_memo[0] [1]), .Y (n_8));
  INVX2 g5263(.A (\MEM_memo[6] [2]), .Y (n_7));
  INVX3 g5284(.A (\MEM_memo[11] [0]), .Y (n_6));
  INVX3 g5297(.A (\MEM_memo[13] [0]), .Y (n_5));
  INVX3 g5325(.A (\MEM_memo[0] [7]), .Y (n_4));
  INVX3 g5312(.A (\MEM_memo[12] [5]), .Y (n_3));
  INVX2 g5305(.A (\MEM_memo[11] [4]), .Y (n_2));
  INVX6 g5279(.A (wfull), .Y (n_1));
  INVX3 g5265(.A (\MEM_memo[14] [7]), .Y (n_0));
  INVX4 g5289(.A (rptr[4]), .Y (n_157));
  INVX8 g5328(.A (waddr[3]), .Y (n_112));
  INVX4 g5329(.A (raddr[0]), .Y (n_78));
  INVX16 g5330(.A (waddr[0]), .Y (n_118));
endmodule

